// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedwaterheater

import mock "github.com/stretchr/testify/mock"

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// SetWaterHeaterMode provides a mock function with given fields: mode
func (_m *Controller) SetWaterHeaterMode(mode string) error {
	ret := _m.Called(mode)

	if len(ret) == 0 {
		panic("no return value specified for SetWaterHeaterMode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(mode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_SetWaterHeaterMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWaterHeaterMode'
type Controller_SetWaterHeaterMode_Call struct {
	*mock.Call
}

// SetWaterHeaterMode is a helper method to define mock.On call
//   - mode string
func (_e *Controller_Expecter) SetWaterHeaterMode(mode interface{}) *Controller_SetWaterHeaterMode_Call {
	return &Controller_SetWaterHeaterMode_Call{Call: _e.mock.On("SetWaterHeaterMode", mode)}
}

func (_c *Controller_SetWaterHeaterMode_Call) Run(run func(mode string)) *Controller_SetWaterHeaterMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Controller_SetWaterHeaterMode_Call) Return(_a0 error) *Controller_SetWaterHeaterMode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_SetWaterHeaterMode_Call) RunAndReturn(run func(string) error) *Controller_SetWaterHeaterMode_Call {
	_c.Call.Return(run)
	return _c
}

// SetWaterHeaterSetpoint provides a mock function with given fields: mode, value, unit
func (_m *Controller) SetWaterHeaterSetpoint(mode string, value float64, unit string) error {
	ret := _m.Called(mode, value, unit)

	if len(ret) == 0 {
		panic("no return value specified for SetWaterHeaterSetpoint")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64, string) error); ok {
		r0 = rf(mode, value, unit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_SetWaterHeaterSetpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWaterHeaterSetpoint'
type Controller_SetWaterHeaterSetpoint_Call struct {
	*mock.Call
}

// SetWaterHeaterSetpoint is a helper method to define mock.On call
//   - mode string
//   - value float64
//   - unit string
func (_e *Controller_Expecter) SetWaterHeaterSetpoint(mode interface{}, value interface{}, unit interface{}) *Controller_SetWaterHeaterSetpoint_Call {
	return &Controller_SetWaterHeaterSetpoint_Call{Call: _e.mock.On("SetWaterHeaterSetpoint", mode, value, unit)}
}

func (_c *Controller_SetWaterHeaterSetpoint_Call) Run(run func(mode string, value float64, unit string)) *Controller_SetWaterHeaterSetpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(float64), args[2].(string))
	})
	return _c
}

func (_c *Controller_SetWaterHeaterSetpoint_Call) Return(_a0 error) *Controller_SetWaterHeaterSetpoint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_SetWaterHeaterSetpoint_Call) RunAndReturn(run func(string, float64, string) error) *Controller_SetWaterHeaterSetpoint_Call {
	_c.Call.Return(run)
	return _c
}

// WaterHeaterModeReport provides a mock function with no fields
func (_m *Controller) WaterHeaterModeReport() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WaterHeaterModeReport")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_WaterHeaterModeReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaterHeaterModeReport'
type Controller_WaterHeaterModeReport_Call struct {
	*mock.Call
}

// WaterHeaterModeReport is a helper method to define mock.On call
func (_e *Controller_Expecter) WaterHeaterModeReport() *Controller_WaterHeaterModeReport_Call {
	return &Controller_WaterHeaterModeReport_Call{Call: _e.mock.On("WaterHeaterModeReport")}
}

func (_c *Controller_WaterHeaterModeReport_Call) Run(run func()) *Controller_WaterHeaterModeReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_WaterHeaterModeReport_Call) Return(mode string, err error) *Controller_WaterHeaterModeReport_Call {
	_c.Call.Return(mode, err)
	return _c
}

func (_c *Controller_WaterHeaterModeReport_Call) RunAndReturn(run func() (string, error)) *Controller_WaterHeaterModeReport_Call {
	_c.Call.Return(run)
	return _c
}

// WaterHeaterSetpointReport provides a mock function with given fields: mode
func (_m *Controller) WaterHeaterSetpointReport(mode string) (float64, string, error) {
	ret := _m.Called(mode)

	if len(ret) == 0 {
		panic("no return value specified for WaterHeaterSetpointReport")
	}

	var r0 float64
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (float64, string, error)); ok {
		return rf(mode)
	}
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(mode)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(mode)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(mode)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Controller_WaterHeaterSetpointReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaterHeaterSetpointReport'
type Controller_WaterHeaterSetpointReport_Call struct {
	*mock.Call
}

// WaterHeaterSetpointReport is a helper method to define mock.On call
//   - mode string
func (_e *Controller_Expecter) WaterHeaterSetpointReport(mode interface{}) *Controller_WaterHeaterSetpointReport_Call {
	return &Controller_WaterHeaterSetpointReport_Call{Call: _e.mock.On("WaterHeaterSetpointReport", mode)}
}

func (_c *Controller_WaterHeaterSetpointReport_Call) Run(run func(mode string)) *Controller_WaterHeaterSetpointReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Controller_WaterHeaterSetpointReport_Call) Return(value float64, unit string, err error) *Controller_WaterHeaterSetpointReport_Call {
	_c.Call.Return(value, unit, err)
	return _c
}

func (_c *Controller_WaterHeaterSetpointReport_Call) RunAndReturn(run func(string) (float64, string, error)) *Controller_WaterHeaterSetpointReport_Call {
	_c.Call.Return(run)
	return _c
}

// WaterHeaterStateReport provides a mock function with no fields
func (_m *Controller) WaterHeaterStateReport() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WaterHeaterStateReport")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_WaterHeaterStateReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaterHeaterStateReport'
type Controller_WaterHeaterStateReport_Call struct {
	*mock.Call
}

// WaterHeaterStateReport is a helper method to define mock.On call
func (_e *Controller_Expecter) WaterHeaterStateReport() *Controller_WaterHeaterStateReport_Call {
	return &Controller_WaterHeaterStateReport_Call{Call: _e.mock.On("WaterHeaterStateReport")}
}

func (_c *Controller_WaterHeaterStateReport_Call) Run(run func()) *Controller_WaterHeaterStateReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_WaterHeaterStateReport_Call) Return(_a0 string, _a1 error) *Controller_WaterHeaterStateReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_WaterHeaterStateReport_Call) RunAndReturn(run func() (string, error)) *Controller_WaterHeaterStateReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
