// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedthermostat

import mock "github.com/stretchr/testify/mock"

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// SetThermostatMode provides a mock function with given fields: mode
func (_m *Controller) SetThermostatMode(mode string) error {
	ret := _m.Called(mode)

	if len(ret) == 0 {
		panic("no return value specified for SetThermostatMode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(mode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_SetThermostatMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetThermostatMode'
type Controller_SetThermostatMode_Call struct {
	*mock.Call
}

// SetThermostatMode is a helper method to define mock.On call
//   - mode string
func (_e *Controller_Expecter) SetThermostatMode(mode interface{}) *Controller_SetThermostatMode_Call {
	return &Controller_SetThermostatMode_Call{Call: _e.mock.On("SetThermostatMode", mode)}
}

func (_c *Controller_SetThermostatMode_Call) Run(run func(mode string)) *Controller_SetThermostatMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Controller_SetThermostatMode_Call) Return(_a0 error) *Controller_SetThermostatMode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_SetThermostatMode_Call) RunAndReturn(run func(string) error) *Controller_SetThermostatMode_Call {
	_c.Call.Return(run)
	return _c
}

// SetThermostatSetpoint provides a mock function with given fields: mode, value, unit
func (_m *Controller) SetThermostatSetpoint(mode string, value float64, unit string) error {
	ret := _m.Called(mode, value, unit)

	if len(ret) == 0 {
		panic("no return value specified for SetThermostatSetpoint")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64, string) error); ok {
		r0 = rf(mode, value, unit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_SetThermostatSetpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetThermostatSetpoint'
type Controller_SetThermostatSetpoint_Call struct {
	*mock.Call
}

// SetThermostatSetpoint is a helper method to define mock.On call
//   - mode string
//   - value float64
//   - unit string
func (_e *Controller_Expecter) SetThermostatSetpoint(mode interface{}, value interface{}, unit interface{}) *Controller_SetThermostatSetpoint_Call {
	return &Controller_SetThermostatSetpoint_Call{Call: _e.mock.On("SetThermostatSetpoint", mode, value, unit)}
}

func (_c *Controller_SetThermostatSetpoint_Call) Run(run func(mode string, value float64, unit string)) *Controller_SetThermostatSetpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(float64), args[2].(string))
	})
	return _c
}

func (_c *Controller_SetThermostatSetpoint_Call) Return(_a0 error) *Controller_SetThermostatSetpoint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_SetThermostatSetpoint_Call) RunAndReturn(run func(string, float64, string) error) *Controller_SetThermostatSetpoint_Call {
	_c.Call.Return(run)
	return _c
}

// ThermostatModeReport provides a mock function with no fields
func (_m *Controller) ThermostatModeReport() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ThermostatModeReport")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_ThermostatModeReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThermostatModeReport'
type Controller_ThermostatModeReport_Call struct {
	*mock.Call
}

// ThermostatModeReport is a helper method to define mock.On call
func (_e *Controller_Expecter) ThermostatModeReport() *Controller_ThermostatModeReport_Call {
	return &Controller_ThermostatModeReport_Call{Call: _e.mock.On("ThermostatModeReport")}
}

func (_c *Controller_ThermostatModeReport_Call) Run(run func()) *Controller_ThermostatModeReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_ThermostatModeReport_Call) Return(mode string, err error) *Controller_ThermostatModeReport_Call {
	_c.Call.Return(mode, err)
	return _c
}

func (_c *Controller_ThermostatModeReport_Call) RunAndReturn(run func() (string, error)) *Controller_ThermostatModeReport_Call {
	_c.Call.Return(run)
	return _c
}

// ThermostatSetpointReport provides a mock function with given fields: mode
func (_m *Controller) ThermostatSetpointReport(mode string) (float64, string, error) {
	ret := _m.Called(mode)

	if len(ret) == 0 {
		panic("no return value specified for ThermostatSetpointReport")
	}

	var r0 float64
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (float64, string, error)); ok {
		return rf(mode)
	}
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(mode)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(mode)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(mode)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Controller_ThermostatSetpointReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThermostatSetpointReport'
type Controller_ThermostatSetpointReport_Call struct {
	*mock.Call
}

// ThermostatSetpointReport is a helper method to define mock.On call
//   - mode string
func (_e *Controller_Expecter) ThermostatSetpointReport(mode interface{}) *Controller_ThermostatSetpointReport_Call {
	return &Controller_ThermostatSetpointReport_Call{Call: _e.mock.On("ThermostatSetpointReport", mode)}
}

func (_c *Controller_ThermostatSetpointReport_Call) Run(run func(mode string)) *Controller_ThermostatSetpointReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Controller_ThermostatSetpointReport_Call) Return(value float64, unit string, err error) *Controller_ThermostatSetpointReport_Call {
	_c.Call.Return(value, unit, err)
	return _c
}

func (_c *Controller_ThermostatSetpointReport_Call) RunAndReturn(run func(string) (float64, string, error)) *Controller_ThermostatSetpointReport_Call {
	_c.Call.Return(run)
	return _c
}

// ThermostatStateReport provides a mock function with no fields
func (_m *Controller) ThermostatStateReport() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ThermostatStateReport")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_ThermostatStateReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThermostatStateReport'
type Controller_ThermostatStateReport_Call struct {
	*mock.Call
}

// ThermostatStateReport is a helper method to define mock.On call
func (_e *Controller_Expecter) ThermostatStateReport() *Controller_ThermostatStateReport_Call {
	return &Controller_ThermostatStateReport_Call{Call: _e.mock.On("ThermostatStateReport")}
}

func (_c *Controller_ThermostatStateReport_Call) Run(run func()) *Controller_ThermostatStateReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_ThermostatStateReport_Call) Return(_a0 string, _a1 error) *Controller_ThermostatStateReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_ThermostatStateReport_Call) RunAndReturn(run func() (string, error)) *Controller_ThermostatStateReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
