// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockeddatabase

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

type Database_Expecter struct {
	mock *mock.Mock
}

func (_m *Database) EXPECT() *Database_Expecter {
	return &Database_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: bucket, key
func (_m *Database) Delete(bucket string, key string) error {
	ret := _m.Called(bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(bucket, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Database_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Database_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - bucket string
//   - key string
func (_e *Database_Expecter) Delete(bucket interface{}, key interface{}) *Database_Delete_Call {
	return &Database_Delete_Call{Call: _e.mock.On("Delete", bucket, key)}
}

func (_c *Database_Delete_Call) Run(run func(bucket string, key string)) *Database_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Database_Delete_Call) Return(_a0 error) *Database_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Database_Delete_Call) RunAndReturn(run func(string, string) error) *Database_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: bucket, key, value
func (_m *Database) Get(bucket string, key string, value interface{}) (bool, error) {
	ret := _m.Called(bucket, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, interface{}) (bool, error)); ok {
		return rf(bucket, key, value)
	}
	if rf, ok := ret.Get(0).(func(string, string, interface{}) bool); ok {
		r0 = rf(bucket, key, value)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string, interface{}) error); ok {
		r1 = rf(bucket, key, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Database_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Database_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - bucket string
//   - key string
//   - value interface{}
func (_e *Database_Expecter) Get(bucket interface{}, key interface{}, value interface{}) *Database_Get_Call {
	return &Database_Get_Call{Call: _e.mock.On("Get", bucket, key, value)}
}

func (_c *Database_Get_Call) Run(run func(bucket string, key string, value interface{})) *Database_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *Database_Get_Call) Return(ok bool, err error) *Database_Get_Call {
	_c.Call.Return(ok, err)
	return _c
}

func (_c *Database_Get_Call) RunAndReturn(run func(string, string, interface{}) (bool, error)) *Database_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Keys provides a mock function with given fields: bucket
func (_m *Database) Keys(bucket string) ([]string, error) {
	ret := _m.Called(bucket)

	if len(ret) == 0 {
		panic("no return value specified for Keys")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(bucket)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(bucket)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(bucket)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Database_Keys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keys'
type Database_Keys_Call struct {
	*mock.Call
}

// Keys is a helper method to define mock.On call
//   - bucket string
func (_e *Database_Expecter) Keys(bucket interface{}) *Database_Keys_Call {
	return &Database_Keys_Call{Call: _e.mock.On("Keys", bucket)}
}

func (_c *Database_Keys_Call) Run(run func(bucket string)) *Database_Keys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Database_Keys_Call) Return(_a0 []string, _a1 error) *Database_Keys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Database_Keys_Call) RunAndReturn(run func(string) ([]string, error)) *Database_Keys_Call {
	_c.Call.Return(run)
	return _c
}

// KeysBetween provides a mock function with given fields: bucket, from, to
func (_m *Database) KeysBetween(bucket string, from string, to string) ([]string, error) {
	ret := _m.Called(bucket, from, to)

	if len(ret) == 0 {
		panic("no return value specified for KeysBetween")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) ([]string, error)); ok {
		return rf(bucket, from, to)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) []string); ok {
		r0 = rf(bucket, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(bucket, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Database_KeysBetween_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeysBetween'
type Database_KeysBetween_Call struct {
	*mock.Call
}

// KeysBetween is a helper method to define mock.On call
//   - bucket string
//   - from string
//   - to string
func (_e *Database_Expecter) KeysBetween(bucket interface{}, from interface{}, to interface{}) *Database_KeysBetween_Call {
	return &Database_KeysBetween_Call{Call: _e.mock.On("KeysBetween", bucket, from, to)}
}

func (_c *Database_KeysBetween_Call) Run(run func(bucket string, from string, to string)) *Database_KeysBetween_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Database_KeysBetween_Call) Return(_a0 []string, _a1 error) *Database_KeysBetween_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Database_KeysBetween_Call) RunAndReturn(run func(string, string, string) ([]string, error)) *Database_KeysBetween_Call {
	_c.Call.Return(run)
	return _c
}

// KeysFrom provides a mock function with given fields: bucket, from
func (_m *Database) KeysFrom(bucket string, from string) ([]string, error) {
	ret := _m.Called(bucket, from)

	if len(ret) == 0 {
		panic("no return value specified for KeysFrom")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]string, error)); ok {
		return rf(bucket, from)
	}
	if rf, ok := ret.Get(0).(func(string, string) []string); ok {
		r0 = rf(bucket, from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(bucket, from)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Database_KeysFrom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeysFrom'
type Database_KeysFrom_Call struct {
	*mock.Call
}

// KeysFrom is a helper method to define mock.On call
//   - bucket string
//   - from string
func (_e *Database_Expecter) KeysFrom(bucket interface{}, from interface{}) *Database_KeysFrom_Call {
	return &Database_KeysFrom_Call{Call: _e.mock.On("KeysFrom", bucket, from)}
}

func (_c *Database_KeysFrom_Call) Run(run func(bucket string, from string)) *Database_KeysFrom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Database_KeysFrom_Call) Return(_a0 []string, _a1 error) *Database_KeysFrom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Database_KeysFrom_Call) RunAndReturn(run func(string, string) ([]string, error)) *Database_KeysFrom_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function with no fields
func (_m *Database) Reset() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Database_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type Database_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *Database_Expecter) Reset() *Database_Reset_Call {
	return &Database_Reset_Call{Call: _e.mock.On("Reset")}
}

func (_c *Database_Reset_Call) Run(run func()) *Database_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Database_Reset_Call) Return(_a0 error) *Database_Reset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Database_Reset_Call) RunAndReturn(run func() error) *Database_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: bucket, key, value
func (_m *Database) Set(bucket string, key string, value interface{}) error {
	ret := _m.Called(bucket, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, interface{}) error); ok {
		r0 = rf(bucket, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Database_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Database_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - bucket string
//   - key string
//   - value interface{}
func (_e *Database_Expecter) Set(bucket interface{}, key interface{}, value interface{}) *Database_Set_Call {
	return &Database_Set_Call{Call: _e.mock.On("Set", bucket, key, value)}
}

func (_c *Database_Set_Call) Run(run func(bucket string, key string, value interface{})) *Database_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *Database_Set_Call) Return(_a0 error) *Database_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Database_Set_Call) RunAndReturn(run func(string, string, interface{}) error) *Database_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetWithExpiry provides a mock function with given fields: bucket, key, value, expiry
func (_m *Database) SetWithExpiry(bucket string, key string, value interface{}, expiry time.Duration) error {
	ret := _m.Called(bucket, key, value, expiry)

	if len(ret) == 0 {
		panic("no return value specified for SetWithExpiry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, interface{}, time.Duration) error); ok {
		r0 = rf(bucket, key, value, expiry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Database_SetWithExpiry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWithExpiry'
type Database_SetWithExpiry_Call struct {
	*mock.Call
}

// SetWithExpiry is a helper method to define mock.On call
//   - bucket string
//   - key string
//   - value interface{}
//   - expiry time.Duration
func (_e *Database_Expecter) SetWithExpiry(bucket interface{}, key interface{}, value interface{}, expiry interface{}) *Database_SetWithExpiry_Call {
	return &Database_SetWithExpiry_Call{Call: _e.mock.On("SetWithExpiry", bucket, key, value, expiry)}
}

func (_c *Database_SetWithExpiry_Call) Run(run func(bucket string, key string, value interface{}, expiry time.Duration)) *Database_SetWithExpiry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *Database_SetWithExpiry_Call) Return(_a0 error) *Database_SetWithExpiry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Database_SetWithExpiry_Call) RunAndReturn(run func(string, string, interface{}, time.Duration) error) *Database_SetWithExpiry_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with no fields
func (_m *Database) Start() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Database_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Database_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *Database_Expecter) Start() *Database_Start_Call {
	return &Database_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *Database_Start_Call) Run(run func()) *Database_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Database_Start_Call) Return(_a0 error) *Database_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Database_Start_Call) RunAndReturn(run func() error) *Database_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *Database) Stop() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Database_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Database_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *Database_Expecter) Stop() *Database_Stop_Call {
	return &Database_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *Database_Stop_Call) Run(run func()) *Database_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Database_Stop_Call) Return(_a0 error) *Database_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Database_Stop_Call) RunAndReturn(run func() error) *Database_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewDatabase creates a new instance of Database. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Database {
	mock := &Database{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
