language: go

go:
  - "1.19"

services:
  - docker

before_script:
  - docker run -d -p 11883:1883 eclipse-mosquitto:1.6.8
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.1
  - go install github.com/mattn/goveralls@latest

script:
  - golangci-lint run ./... --timeout 2m
  - go test -p 1 -v -covermode=atomic -coverprofile=profile_full.cov -coverpkg=./... ./...
  - cat profile_full.cov | grep -v .pb.go | grep -v mock | grep -v test > profile.cov;
  - goveralls -coverprofile=profile.cov -service=travis-pro -repotoken B8NnLqJBg7cuw4oChepQJNnyZ9Tcg5Izy || true
