// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockeddiagnostic

import mock "github.com/stretchr/testify/mock"

// ErrorsReporter is an autogenerated mock type for the ErrorsReporter type
type ErrorsReporter struct {
	mock.Mock
}

type ErrorsReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *ErrorsReporter) EXPECT() *ErrorsReporter_Expecter {
	return &ErrorsReporter_Expecter{mock: &_m.Mock}
}

// ErrorsReport provides a mock function with no fields
func (_m *ErrorsReporter) ErrorsReport() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ErrorsReport")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ErrorsReporter_ErrorsReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorsReport'
type ErrorsReporter_ErrorsReport_Call struct {
	*mock.Call
}

// ErrorsReport is a helper method to define mock.On call
func (_e *ErrorsReporter_Expecter) ErrorsReport() *ErrorsReporter_ErrorsReport_Call {
	return &ErrorsReporter_ErrorsReport_Call{Call: _e.mock.On("ErrorsReport")}
}

func (_c *ErrorsReporter_ErrorsReport_Call) Run(run func()) *ErrorsReporter_ErrorsReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ErrorsReporter_ErrorsReport_Call) Return(_a0 []string, _a1 error) *ErrorsReporter_ErrorsReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ErrorsReporter_ErrorsReport_Call) RunAndReturn(run func() ([]string, error)) *ErrorsReporter_ErrorsReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewErrorsReporter creates a new instance of ErrorsReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorsReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorsReporter {
	mock := &ErrorsReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
