// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockeddiagnostic

import mock "github.com/stretchr/testify/mock"

// LQIReporter is an autogenerated mock type for the LQIReporter type
type LQIReporter struct {
	mock.Mock
}

type LQIReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *LQIReporter) EXPECT() *LQIReporter_Expecter {
	return &LQIReporter_Expecter{mock: &_m.Mock}
}

// LQIReport provides a mock function with no fields
func (_m *LQIReporter) LQIReport() (int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LQIReport")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LQIReporter_LQIReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LQIReport'
type LQIReporter_LQIReport_Call struct {
	*mock.Call
}

// LQIReport is a helper method to define mock.On call
func (_e *LQIReporter_Expecter) LQIReport() *LQIReporter_LQIReport_Call {
	return &LQIReporter_LQIReport_Call{Call: _e.mock.On("LQIReport")}
}

func (_c *LQIReporter_LQIReport_Call) Run(run func()) *LQIReporter_LQIReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LQIReporter_LQIReport_Call) Return(_a0 int, _a1 error) *LQIReporter_LQIReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LQIReporter_LQIReport_Call) RunAndReturn(run func() (int, error)) *LQIReporter_LQIReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewLQIReporter creates a new instance of LQIReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLQIReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *LQIReporter {
	mock := &LQIReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
