// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockeddiagnostic

import mock "github.com/stretchr/testify/mock"

// RebootReasonReporter is an autogenerated mock type for the RebootReasonReporter type
type RebootReasonReporter struct {
	mock.Mock
}

type RebootReasonReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *RebootReasonReporter) EXPECT() *RebootReasonReporter_Expecter {
	return &RebootReasonReporter_Expecter{mock: &_m.Mock}
}

// RebootReasonReport provides a mock function with no fields
func (_m *RebootReasonReporter) RebootReasonReport() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RebootReasonReport")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RebootReasonReporter_RebootReasonReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RebootReasonReport'
type RebootReasonReporter_RebootReasonReport_Call struct {
	*mock.Call
}

// RebootReasonReport is a helper method to define mock.On call
func (_e *RebootReasonReporter_Expecter) RebootReasonReport() *RebootReasonReporter_RebootReasonReport_Call {
	return &RebootReasonReporter_RebootReasonReport_Call{Call: _e.mock.On("RebootReasonReport")}
}

func (_c *RebootReasonReporter_RebootReasonReport_Call) Run(run func()) *RebootReasonReporter_RebootReasonReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RebootReasonReporter_RebootReasonReport_Call) Return(_a0 string, _a1 error) *RebootReasonReporter_RebootReasonReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RebootReasonReporter_RebootReasonReport_Call) RunAndReturn(run func() (string, error)) *RebootReasonReporter_RebootReasonReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewRebootReasonReporter creates a new instance of RebootReasonReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRebootReasonReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *RebootReasonReporter {
	mock := &RebootReasonReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
