// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockeddiagnostic

import mock "github.com/stretchr/testify/mock"

// RebootsCountReporter is an autogenerated mock type for the RebootsCountReporter type
type RebootsCountReporter struct {
	mock.Mock
}

type RebootsCountReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *RebootsCountReporter) EXPECT() *RebootsCountReporter_Expecter {
	return &RebootsCountReporter_Expecter{mock: &_m.Mock}
}

// RebootsCountReport provides a mock function with no fields
func (_m *RebootsCountReporter) RebootsCountReport() (int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RebootsCountReport")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RebootsCountReporter_RebootsCountReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RebootsCountReport'
type RebootsCountReporter_RebootsCountReport_Call struct {
	*mock.Call
}

// RebootsCountReport is a helper method to define mock.On call
func (_e *RebootsCountReporter_Expecter) RebootsCountReport() *RebootsCountReporter_RebootsCountReport_Call {
	return &RebootsCountReporter_RebootsCountReport_Call{Call: _e.mock.On("RebootsCountReport")}
}

func (_c *RebootsCountReporter_RebootsCountReport_Call) Run(run func()) *RebootsCountReporter_RebootsCountReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RebootsCountReporter_RebootsCountReport_Call) Return(_a0 int, _a1 error) *RebootsCountReporter_RebootsCountReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RebootsCountReporter_RebootsCountReport_Call) RunAndReturn(run func() (int, error)) *RebootsCountReporter_RebootsCountReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewRebootsCountReporter creates a new instance of RebootsCountReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRebootsCountReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *RebootsCountReporter {
	mock := &RebootsCountReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
