// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockeddiagnostic

import (
	adapter "github.com/futurehomeno/cliffhanger/adapter"

	fimpgo "github.com/futurehomeno/fimpgo"

	fimptype "github.com/futurehomeno/fimpgo/fimptype"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with no fields
func (_m *Service) Name() fimptype.ServiceNameT {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 fimptype.ServiceNameT
	if rf, ok := ret.Get(0).(func() fimptype.ServiceNameT); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(fimptype.ServiceNameT)
	}

	return r0
}

// Service_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Service_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Service_Expecter) Name() *Service_Name_Call {
	return &Service_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Service_Name_Call) Run(run func()) *Service_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Name_Call) Return(_a0 fimptype.ServiceNameT) *Service_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Name_Call) RunAndReturn(run func() fimptype.ServiceNameT) *Service_Name_Call {
	_c.Call.Return(run)
	return _c
}

// PublishEvent provides a mock function with given fields: event
func (_m *Service) PublishEvent(event adapter.ServiceEvent) {
	_m.Called(event)
}

// Service_PublishEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishEvent'
type Service_PublishEvent_Call struct {
	*mock.Call
}

// PublishEvent is a helper method to define mock.On call
//   - event adapter.ServiceEvent
func (_e *Service_Expecter) PublishEvent(event interface{}) *Service_PublishEvent_Call {
	return &Service_PublishEvent_Call{Call: _e.mock.On("PublishEvent", event)}
}

func (_c *Service_PublishEvent_Call) Run(run func(event adapter.ServiceEvent)) *Service_PublishEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(adapter.ServiceEvent))
	})
	return _c
}

func (_c *Service_PublishEvent_Call) Return() *Service_PublishEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *Service_PublishEvent_Call) RunAndReturn(run func(adapter.ServiceEvent)) *Service_PublishEvent_Call {
	_c.Run(run)
	return _c
}

// SendErrorsReport provides a mock function with no fields
func (_m *Service) SendErrorsReport() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendErrorsReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_SendErrorsReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendErrorsReport'
type Service_SendErrorsReport_Call struct {
	*mock.Call
}

// SendErrorsReport is a helper method to define mock.On call
func (_e *Service_Expecter) SendErrorsReport() *Service_SendErrorsReport_Call {
	return &Service_SendErrorsReport_Call{Call: _e.mock.On("SendErrorsReport")}
}

func (_c *Service_SendErrorsReport_Call) Run(run func()) *Service_SendErrorsReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_SendErrorsReport_Call) Return(_a0 error) *Service_SendErrorsReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SendErrorsReport_Call) RunAndReturn(run func() error) *Service_SendErrorsReport_Call {
	_c.Call.Return(run)
	return _c
}

// SendLQIReport provides a mock function with no fields
func (_m *Service) SendLQIReport() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendLQIReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_SendLQIReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendLQIReport'
type Service_SendLQIReport_Call struct {
	*mock.Call
}

// SendLQIReport is a helper method to define mock.On call
func (_e *Service_Expecter) SendLQIReport() *Service_SendLQIReport_Call {
	return &Service_SendLQIReport_Call{Call: _e.mock.On("SendLQIReport")}
}

func (_c *Service_SendLQIReport_Call) Run(run func()) *Service_SendLQIReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_SendLQIReport_Call) Return(_a0 error) *Service_SendLQIReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SendLQIReport_Call) RunAndReturn(run func() error) *Service_SendLQIReport_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function with given fields: message
func (_m *Service) SendMessage(message *fimpgo.FimpMessage) error {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fimpgo.FimpMessage) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type Service_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - message *fimpgo.FimpMessage
func (_e *Service_Expecter) SendMessage(message interface{}) *Service_SendMessage_Call {
	return &Service_SendMessage_Call{Call: _e.mock.On("SendMessage", message)}
}

func (_c *Service_SendMessage_Call) Run(run func(message *fimpgo.FimpMessage)) *Service_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fimpgo.FimpMessage))
	})
	return _c
}

func (_c *Service_SendMessage_Call) Return(_a0 error) *Service_SendMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SendMessage_Call) RunAndReturn(run func(*fimpgo.FimpMessage) error) *Service_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendRSSIReport provides a mock function with no fields
func (_m *Service) SendRSSIReport() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendRSSIReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_SendRSSIReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRSSIReport'
type Service_SendRSSIReport_Call struct {
	*mock.Call
}

// SendRSSIReport is a helper method to define mock.On call
func (_e *Service_Expecter) SendRSSIReport() *Service_SendRSSIReport_Call {
	return &Service_SendRSSIReport_Call{Call: _e.mock.On("SendRSSIReport")}
}

func (_c *Service_SendRSSIReport_Call) Run(run func()) *Service_SendRSSIReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_SendRSSIReport_Call) Return(_a0 error) *Service_SendRSSIReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SendRSSIReport_Call) RunAndReturn(run func() error) *Service_SendRSSIReport_Call {
	_c.Call.Return(run)
	return _c
}

// SendRebootReasonReport provides a mock function with no fields
func (_m *Service) SendRebootReasonReport() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendRebootReasonReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_SendRebootReasonReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRebootReasonReport'
type Service_SendRebootReasonReport_Call struct {
	*mock.Call
}

// SendRebootReasonReport is a helper method to define mock.On call
func (_e *Service_Expecter) SendRebootReasonReport() *Service_SendRebootReasonReport_Call {
	return &Service_SendRebootReasonReport_Call{Call: _e.mock.On("SendRebootReasonReport")}
}

func (_c *Service_SendRebootReasonReport_Call) Run(run func()) *Service_SendRebootReasonReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_SendRebootReasonReport_Call) Return(_a0 error) *Service_SendRebootReasonReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SendRebootReasonReport_Call) RunAndReturn(run func() error) *Service_SendRebootReasonReport_Call {
	_c.Call.Return(run)
	return _c
}

// SendRebootsCountReport provides a mock function with no fields
func (_m *Service) SendRebootsCountReport() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendRebootsCountReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_SendRebootsCountReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRebootsCountReport'
type Service_SendRebootsCountReport_Call struct {
	*mock.Call
}

// SendRebootsCountReport is a helper method to define mock.On call
func (_e *Service_Expecter) SendRebootsCountReport() *Service_SendRebootsCountReport_Call {
	return &Service_SendRebootsCountReport_Call{Call: _e.mock.On("SendRebootsCountReport")}
}

func (_c *Service_SendRebootsCountReport_Call) Run(run func()) *Service_SendRebootsCountReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_SendRebootsCountReport_Call) Return(_a0 error) *Service_SendRebootsCountReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SendRebootsCountReport_Call) RunAndReturn(run func() error) *Service_SendRebootsCountReport_Call {
	_c.Call.Return(run)
	return _c
}

// SendUptimeReport provides a mock function with no fields
func (_m *Service) SendUptimeReport() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendUptimeReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_SendUptimeReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUptimeReport'
type Service_SendUptimeReport_Call struct {
	*mock.Call
}

// SendUptimeReport is a helper method to define mock.On call
func (_e *Service_Expecter) SendUptimeReport() *Service_SendUptimeReport_Call {
	return &Service_SendUptimeReport_Call{Call: _e.mock.On("SendUptimeReport")}
}

func (_c *Service_SendUptimeReport_Call) Run(run func()) *Service_SendUptimeReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_SendUptimeReport_Call) Return(_a0 error) *Service_SendUptimeReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SendUptimeReport_Call) RunAndReturn(run func() error) *Service_SendUptimeReport_Call {
	_c.Call.Return(run)
	return _c
}

// Specification provides a mock function with no fields
func (_m *Service) Specification() *fimptype.Service {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Specification")
	}

	var r0 *fimptype.Service
	if rf, ok := ret.Get(0).(func() *fimptype.Service); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fimptype.Service)
		}
	}

	return r0
}

// Service_Specification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Specification'
type Service_Specification_Call struct {
	*mock.Call
}

// Specification is a helper method to define mock.On call
func (_e *Service_Expecter) Specification() *Service_Specification_Call {
	return &Service_Specification_Call{Call: _e.mock.On("Specification")}
}

func (_c *Service_Specification_Call) Run(run func()) *Service_Specification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Specification_Call) Return(_a0 *fimptype.Service) *Service_Specification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Specification_Call) RunAndReturn(run func() *fimptype.Service) *Service_Specification_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsErrors provides a mock function with no fields
func (_m *Service) SupportsErrors() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsErrors")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Service_SupportsErrors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsErrors'
type Service_SupportsErrors_Call struct {
	*mock.Call
}

// SupportsErrors is a helper method to define mock.On call
func (_e *Service_Expecter) SupportsErrors() *Service_SupportsErrors_Call {
	return &Service_SupportsErrors_Call{Call: _e.mock.On("SupportsErrors")}
}

func (_c *Service_SupportsErrors_Call) Run(run func()) *Service_SupportsErrors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_SupportsErrors_Call) Return(_a0 bool) *Service_SupportsErrors_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SupportsErrors_Call) RunAndReturn(run func() bool) *Service_SupportsErrors_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsLQI provides a mock function with no fields
func (_m *Service) SupportsLQI() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsLQI")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Service_SupportsLQI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsLQI'
type Service_SupportsLQI_Call struct {
	*mock.Call
}

// SupportsLQI is a helper method to define mock.On call
func (_e *Service_Expecter) SupportsLQI() *Service_SupportsLQI_Call {
	return &Service_SupportsLQI_Call{Call: _e.mock.On("SupportsLQI")}
}

func (_c *Service_SupportsLQI_Call) Run(run func()) *Service_SupportsLQI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_SupportsLQI_Call) Return(_a0 bool) *Service_SupportsLQI_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SupportsLQI_Call) RunAndReturn(run func() bool) *Service_SupportsLQI_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsRSSI provides a mock function with no fields
func (_m *Service) SupportsRSSI() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsRSSI")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Service_SupportsRSSI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsRSSI'
type Service_SupportsRSSI_Call struct {
	*mock.Call
}

// SupportsRSSI is a helper method to define mock.On call
func (_e *Service_Expecter) SupportsRSSI() *Service_SupportsRSSI_Call {
	return &Service_SupportsRSSI_Call{Call: _e.mock.On("SupportsRSSI")}
}

func (_c *Service_SupportsRSSI_Call) Run(run func()) *Service_SupportsRSSI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_SupportsRSSI_Call) Return(_a0 bool) *Service_SupportsRSSI_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SupportsRSSI_Call) RunAndReturn(run func() bool) *Service_SupportsRSSI_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsRebootReason provides a mock function with no fields
func (_m *Service) SupportsRebootReason() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsRebootReason")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Service_SupportsRebootReason_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsRebootReason'
type Service_SupportsRebootReason_Call struct {
	*mock.Call
}

// SupportsRebootReason is a helper method to define mock.On call
func (_e *Service_Expecter) SupportsRebootReason() *Service_SupportsRebootReason_Call {
	return &Service_SupportsRebootReason_Call{Call: _e.mock.On("SupportsRebootReason")}
}

func (_c *Service_SupportsRebootReason_Call) Run(run func()) *Service_SupportsRebootReason_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_SupportsRebootReason_Call) Return(_a0 bool) *Service_SupportsRebootReason_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SupportsRebootReason_Call) RunAndReturn(run func() bool) *Service_SupportsRebootReason_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsRebootsCount provides a mock function with no fields
func (_m *Service) SupportsRebootsCount() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsRebootsCount")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Service_SupportsRebootsCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsRebootsCount'
type Service_SupportsRebootsCount_Call struct {
	*mock.Call
}

// SupportsRebootsCount is a helper method to define mock.On call
func (_e *Service_Expecter) SupportsRebootsCount() *Service_SupportsRebootsCount_Call {
	return &Service_SupportsRebootsCount_Call{Call: _e.mock.On("SupportsRebootsCount")}
}

func (_c *Service_SupportsRebootsCount_Call) Run(run func()) *Service_SupportsRebootsCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_SupportsRebootsCount_Call) Return(_a0 bool) *Service_SupportsRebootsCount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SupportsRebootsCount_Call) RunAndReturn(run func() bool) *Service_SupportsRebootsCount_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsUptime provides a mock function with no fields
func (_m *Service) SupportsUptime() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsUptime")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Service_SupportsUptime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsUptime'
type Service_SupportsUptime_Call struct {
	*mock.Call
}

// SupportsUptime is a helper method to define mock.On call
func (_e *Service_Expecter) SupportsUptime() *Service_SupportsUptime_Call {
	return &Service_SupportsUptime_Call{Call: _e.mock.On("SupportsUptime")}
}

func (_c *Service_SupportsUptime_Call) Run(run func()) *Service_SupportsUptime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_SupportsUptime_Call) Return(_a0 bool) *Service_SupportsUptime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SupportsUptime_Call) RunAndReturn(run func() bool) *Service_SupportsUptime_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function with no fields
func (_m *Service) Topic() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Service_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type Service_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *Service_Expecter) Topic() *Service_Topic_Call {
	return &Service_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *Service_Topic_Call) Run(run func()) *Service_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Topic_Call) Return(_a0 string) *Service_Topic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Topic_Call) RunAndReturn(run func() string) *Service_Topic_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
