// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockeddiagnostic

import mock "github.com/stretchr/testify/mock"

// UptimeReporter is an autogenerated mock type for the UptimeReporter type
type UptimeReporter struct {
	mock.Mock
}

type UptimeReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *UptimeReporter) EXPECT() *UptimeReporter_Expecter {
	return &UptimeReporter_Expecter{mock: &_m.Mock}
}

// UptimeReport provides a mock function with no fields
func (_m *UptimeReporter) UptimeReport() (int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UptimeReport")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UptimeReporter_UptimeReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UptimeReport'
type UptimeReporter_UptimeReport_Call struct {
	*mock.Call
}

// UptimeReport is a helper method to define mock.On call
func (_e *UptimeReporter_Expecter) UptimeReport() *UptimeReporter_UptimeReport_Call {
	return &UptimeReporter_UptimeReport_Call{Call: _e.mock.On("UptimeReport")}
}

func (_c *UptimeReporter_UptimeReport_Call) Run(run func()) *UptimeReporter_UptimeReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UptimeReporter_UptimeReport_Call) Return(_a0 int, _a1 error) *UptimeReporter_UptimeReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UptimeReporter_UptimeReport_Call) RunAndReturn(run func() (int, error)) *UptimeReporter_UptimeReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewUptimeReporter creates a new instance of UptimeReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUptimeReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *UptimeReporter {
	mock := &UptimeReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
