// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedstorage

import mock "github.com/stretchr/testify/mock"

// Storage is an autogenerated mock type for the Storage type
type Storage[T any] struct {
	mock.Mock
}

type Storage_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *Storage[T]) EXPECT() *Storage_Expecter[T] {
	return &Storage_Expecter[T]{mock: &_m.Mock}
}

// Load provides a mock function with no fields
func (_m *Storage[T]) Load() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type Storage_Load_Call[T any] struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *Storage_Expecter[T]) Load() *Storage_Load_Call[T] {
	return &Storage_Load_Call[T]{Call: _e.mock.On("Load")}
}

func (_c *Storage_Load_Call[T]) Run(run func()) *Storage_Load_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Storage_Load_Call[T]) Return(_a0 error) *Storage_Load_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_Load_Call[T]) RunAndReturn(run func() error) *Storage_Load_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Model provides a mock function with no fields
func (_m *Storage[T]) Model() T {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Model")
	}

	var r0 T
	if rf, ok := ret.Get(0).(func() T); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	return r0
}

// Storage_Model_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Model'
type Storage_Model_Call[T any] struct {
	*mock.Call
}

// Model is a helper method to define mock.On call
func (_e *Storage_Expecter[T]) Model() *Storage_Model_Call[T] {
	return &Storage_Model_Call[T]{Call: _e.mock.On("Model")}
}

func (_c *Storage_Model_Call[T]) Run(run func()) *Storage_Model_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Storage_Model_Call[T]) Return(_a0 T) *Storage_Model_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_Model_Call[T]) RunAndReturn(run func() T) *Storage_Model_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function with no fields
func (_m *Storage[T]) Reset() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type Storage_Reset_Call[T any] struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *Storage_Expecter[T]) Reset() *Storage_Reset_Call[T] {
	return &Storage_Reset_Call[T]{Call: _e.mock.On("Reset")}
}

func (_c *Storage_Reset_Call[T]) Run(run func()) *Storage_Reset_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Storage_Reset_Call[T]) Return(_a0 error) *Storage_Reset_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_Reset_Call[T]) RunAndReturn(run func() error) *Storage_Reset_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with no fields
func (_m *Storage[T]) Save() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Storage_Save_Call[T any] struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
func (_e *Storage_Expecter[T]) Save() *Storage_Save_Call[T] {
	return &Storage_Save_Call[T]{Call: _e.mock.On("Save")}
}

func (_c *Storage_Save_Call[T]) Run(run func()) *Storage_Save_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Storage_Save_Call[T]) Return(_a0 error) *Storage_Save_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_Save_Call[T]) RunAndReturn(run func() error) *Storage_Save_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage[T] {
	mock := &Storage[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
