// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedoutbinswitch

import mock "github.com/stretchr/testify/mock"

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// BinarySwitchStateReport provides a mock function with no fields
func (_m *Controller) BinarySwitchStateReport() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BinarySwitchStateReport")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_BinarySwitchStateReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BinarySwitchStateReport'
type Controller_BinarySwitchStateReport_Call struct {
	*mock.Call
}

// BinarySwitchStateReport is a helper method to define mock.On call
func (_e *Controller_Expecter) BinarySwitchStateReport() *Controller_BinarySwitchStateReport_Call {
	return &Controller_BinarySwitchStateReport_Call{Call: _e.mock.On("BinarySwitchStateReport")}
}

func (_c *Controller_BinarySwitchStateReport_Call) Run(run func()) *Controller_BinarySwitchStateReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_BinarySwitchStateReport_Call) Return(_a0 bool, _a1 error) *Controller_BinarySwitchStateReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_BinarySwitchStateReport_Call) RunAndReturn(run func() (bool, error)) *Controller_BinarySwitchStateReport_Call {
	_c.Call.Return(run)
	return _c
}

// SetBinarySwitchState provides a mock function with given fields: _a0
func (_m *Controller) SetBinarySwitchState(_a0 bool) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetBinarySwitchState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_SetBinarySwitchState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBinarySwitchState'
type Controller_SetBinarySwitchState_Call struct {
	*mock.Call
}

// SetBinarySwitchState is a helper method to define mock.On call
//   - _a0 bool
func (_e *Controller_Expecter) SetBinarySwitchState(_a0 interface{}) *Controller_SetBinarySwitchState_Call {
	return &Controller_SetBinarySwitchState_Call{Call: _e.mock.On("SetBinarySwitchState", _a0)}
}

func (_c *Controller_SetBinarySwitchState_Call) Run(run func(_a0 bool)) *Controller_SetBinarySwitchState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *Controller_SetBinarySwitchState_Call) Return(_a0 error) *Controller_SetBinarySwitchState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_SetBinarySwitchState_Call) RunAndReturn(run func(bool) error) *Controller_SetBinarySwitchState_Call {
	_c.Call.Return(run)
	return _c
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
