// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockedalarm

import (
	alarm "github.com/futurehomeno/cliffhanger/adapter/service/alarm"
	mock "github.com/stretchr/testify/mock"
)

// Reporter is an autogenerated mock type for the Reporter type
type Reporter struct {
	mock.Mock
}

type Reporter_Expecter struct {
	mock *mock.Mock
}

func (_m *Reporter) EXPECT() *Reporter_Expecter {
	return &Reporter_Expecter{mock: &_m.Mock}
}

// AlarmReport provides a mock function with given fields: event
func (_m *Reporter) AlarmReport(event string) (*alarm.Report, error) {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for AlarmReport")
	}

	var r0 *alarm.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*alarm.Report, error)); ok {
		return rf(event)
	}
	if rf, ok := ret.Get(0).(func(string) *alarm.Report); ok {
		r0 = rf(event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*alarm.Report)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reporter_AlarmReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AlarmReport'
type Reporter_AlarmReport_Call struct {
	*mock.Call
}

// AlarmReport is a helper method to define mock.On call
//   - event string
func (_e *Reporter_Expecter) AlarmReport(event interface{}) *Reporter_AlarmReport_Call {
	return &Reporter_AlarmReport_Call{Call: _e.mock.On("AlarmReport", event)}
}

func (_c *Reporter_AlarmReport_Call) Run(run func(event string)) *Reporter_AlarmReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Reporter_AlarmReport_Call) Return(_a0 *alarm.Report, _a1 error) *Reporter_AlarmReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Reporter_AlarmReport_Call) RunAndReturn(run func(string) (*alarm.Report, error)) *Reporter_AlarmReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewReporter creates a new instance of Reporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reporter {
	mock := &Reporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
