// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedpresence

import mock "github.com/stretchr/testify/mock"

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// SensorPresenceReport provides a mock function with no fields
func (_m *Controller) SensorPresenceReport() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SensorPresenceReport")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_SensorPresenceReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SensorPresenceReport'
type Controller_SensorPresenceReport_Call struct {
	*mock.Call
}

// SensorPresenceReport is a helper method to define mock.On call
func (_e *Controller_Expecter) SensorPresenceReport() *Controller_SensorPresenceReport_Call {
	return &Controller_SensorPresenceReport_Call{Call: _e.mock.On("SensorPresenceReport")}
}

func (_c *Controller_SensorPresenceReport_Call) Run(run func()) *Controller_SensorPresenceReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_SensorPresenceReport_Call) Return(_a0 bool, _a1 error) *Controller_SensorPresenceReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_SensorPresenceReport_Call) RunAndReturn(run func() (bool, error)) *Controller_SensorPresenceReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
