// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedscenectrl

import (
	scenectrl "github.com/futurehomeno/cliffhanger/adapter/service/scenectrl"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// SceneCtrlSceneReport provides a mock function with no fields
func (_m *Controller) SceneCtrlSceneReport() (scenectrl.SceneReport, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SceneCtrlSceneReport")
	}

	var r0 scenectrl.SceneReport
	var r1 error
	if rf, ok := ret.Get(0).(func() (scenectrl.SceneReport, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() scenectrl.SceneReport); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(scenectrl.SceneReport)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_SceneCtrlSceneReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SceneCtrlSceneReport'
type Controller_SceneCtrlSceneReport_Call struct {
	*mock.Call
}

// SceneCtrlSceneReport is a helper method to define mock.On call
func (_e *Controller_Expecter) SceneCtrlSceneReport() *Controller_SceneCtrlSceneReport_Call {
	return &Controller_SceneCtrlSceneReport_Call{Call: _e.mock.On("SceneCtrlSceneReport")}
}

func (_c *Controller_SceneCtrlSceneReport_Call) Run(run func()) *Controller_SceneCtrlSceneReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_SceneCtrlSceneReport_Call) Return(_a0 scenectrl.SceneReport, _a1 error) *Controller_SceneCtrlSceneReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_SceneCtrlSceneReport_Call) RunAndReturn(run func() (scenectrl.SceneReport, error)) *Controller_SceneCtrlSceneReport_Call {
	_c.Call.Return(run)
	return _c
}

// SetSceneCtrlScene provides a mock function with given fields: scene
func (_m *Controller) SetSceneCtrlScene(scene string) error {
	ret := _m.Called(scene)

	if len(ret) == 0 {
		panic("no return value specified for SetSceneCtrlScene")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(scene)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_SetSceneCtrlScene_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSceneCtrlScene'
type Controller_SetSceneCtrlScene_Call struct {
	*mock.Call
}

// SetSceneCtrlScene is a helper method to define mock.On call
//   - scene string
func (_e *Controller_Expecter) SetSceneCtrlScene(scene any) *Controller_SetSceneCtrlScene_Call {
	return &Controller_SetSceneCtrlScene_Call{Call: _e.mock.On("SetSceneCtrlScene", scene)}
}

func (_c *Controller_SetSceneCtrlScene_Call) Run(run func(scene string)) *Controller_SetSceneCtrlScene_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Controller_SetSceneCtrlScene_Call) Return(_a0 error) *Controller_SetSceneCtrlScene_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_SetSceneCtrlScene_Call) RunAndReturn(run func(string) error) *Controller_SetSceneCtrlScene_Call {
	_c.Call.Return(run)
	return _c
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
