// Code generated by mockery v2.23.1. DO NOT EDIT.

package mockedscenectrl

import (
	scenectrl "github.com/futurehomeno/cliffhanger/adapter/service/scenectrl"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// SceneCtrlSceneReport provides a mock function with given fields:
func (_m *Controller) SceneCtrlSceneReport() (scenectrl.SceneReport, error) {
	ret := _m.Called()

	var r0 scenectrl.SceneReport
	var r1 error
	if rf, ok := ret.Get(0).(func() (scenectrl.SceneReport, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() scenectrl.SceneReport); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(scenectrl.SceneReport)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetSceneCtrlScene provides a mock function with given fields: scene
func (_m *Controller) SetSceneCtrlScene(scene string) error {
	ret := _m.Called(scene)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(scene)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewController interface {
	mock.TestingT
	Cleanup(func())
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewController(t mockConstructorTestingTNewController) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
