// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedcolorctrl

import (
	adapter "github.com/futurehomeno/cliffhanger/adapter"

	fimpgo "github.com/futurehomeno/fimpgo"
	fimptype "github.com/futurehomeno/fimpgo/fimptype"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with no fields
func (_m *Service) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Service_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Service_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Service_Expecter) Name() *Service_Name_Call {
	return &Service_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Service_Name_Call) Run(run func()) *Service_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Name_Call) Return(_a0 string) *Service_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Name_Call) RunAndReturn(run func() string) *Service_Name_Call {
	_c.Call.Return(run)
	return _c
}

// PublishEvent provides a mock function with given fields: event
func (_m *Service) PublishEvent(event adapter.ServiceEvent) {
	_m.Called(event)
}

// Service_PublishEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishEvent'
type Service_PublishEvent_Call struct {
	*mock.Call
}

// PublishEvent is a helper method to define mock.On call
//   - event adapter.ServiceEvent
func (_e *Service_Expecter) PublishEvent(event interface{}) *Service_PublishEvent_Call {
	return &Service_PublishEvent_Call{Call: _e.mock.On("PublishEvent", event)}
}

func (_c *Service_PublishEvent_Call) Run(run func(event adapter.ServiceEvent)) *Service_PublishEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(adapter.ServiceEvent))
	})
	return _c
}

func (_c *Service_PublishEvent_Call) Return() *Service_PublishEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *Service_PublishEvent_Call) RunAndReturn(run func(adapter.ServiceEvent)) *Service_PublishEvent_Call {
	_c.Run(run)
	return _c
}

// SendColorReport provides a mock function with given fields: force
func (_m *Service) SendColorReport(force bool) (bool, error) {
	ret := _m.Called(force)

	if len(ret) == 0 {
		panic("no return value specified for SendColorReport")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(bool) (bool, error)); ok {
		return rf(force)
	}
	if rf, ok := ret.Get(0).(func(bool) bool); ok {
		r0 = rf(force)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(bool) error); ok {
		r1 = rf(force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_SendColorReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendColorReport'
type Service_SendColorReport_Call struct {
	*mock.Call
}

// SendColorReport is a helper method to define mock.On call
//   - force bool
func (_e *Service_Expecter) SendColorReport(force interface{}) *Service_SendColorReport_Call {
	return &Service_SendColorReport_Call{Call: _e.mock.On("SendColorReport", force)}
}

func (_c *Service_SendColorReport_Call) Run(run func(force bool)) *Service_SendColorReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *Service_SendColorReport_Call) Return(_a0 bool, _a1 error) *Service_SendColorReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_SendColorReport_Call) RunAndReturn(run func(bool) (bool, error)) *Service_SendColorReport_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function with given fields: message
func (_m *Service) SendMessage(message *fimpgo.FimpMessage) error {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fimpgo.FimpMessage) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type Service_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - message *fimpgo.FimpMessage
func (_e *Service_Expecter) SendMessage(message interface{}) *Service_SendMessage_Call {
	return &Service_SendMessage_Call{Call: _e.mock.On("SendMessage", message)}
}

func (_c *Service_SendMessage_Call) Run(run func(message *fimpgo.FimpMessage)) *Service_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fimpgo.FimpMessage))
	})
	return _c
}

func (_c *Service_SendMessage_Call) Return(_a0 error) *Service_SendMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SendMessage_Call) RunAndReturn(run func(*fimpgo.FimpMessage) error) *Service_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SetColor provides a mock function with given fields: color
func (_m *Service) SetColor(color map[string]int) error {
	ret := _m.Called(color)

	if len(ret) == 0 {
		panic("no return value specified for SetColor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]int) error); ok {
		r0 = rf(color)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_SetColor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetColor'
type Service_SetColor_Call struct {
	*mock.Call
}

// SetColor is a helper method to define mock.On call
//   - color map[string]int
func (_e *Service_Expecter) SetColor(color interface{}) *Service_SetColor_Call {
	return &Service_SetColor_Call{Call: _e.mock.On("SetColor", color)}
}

func (_c *Service_SetColor_Call) Run(run func(color map[string]int)) *Service_SetColor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]int))
	})
	return _c
}

func (_c *Service_SetColor_Call) Return(_a0 error) *Service_SetColor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SetColor_Call) RunAndReturn(run func(map[string]int) error) *Service_SetColor_Call {
	_c.Call.Return(run)
	return _c
}

// Specification provides a mock function with no fields
func (_m *Service) Specification() *fimptype.Service {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Specification")
	}

	var r0 *fimptype.Service
	if rf, ok := ret.Get(0).(func() *fimptype.Service); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fimptype.Service)
		}
	}

	return r0
}

// Service_Specification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Specification'
type Service_Specification_Call struct {
	*mock.Call
}

// Specification is a helper method to define mock.On call
func (_e *Service_Expecter) Specification() *Service_Specification_Call {
	return &Service_Specification_Call{Call: _e.mock.On("Specification")}
}

func (_c *Service_Specification_Call) Run(run func()) *Service_Specification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Specification_Call) Return(_a0 *fimptype.Service) *Service_Specification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Specification_Call) RunAndReturn(run func() *fimptype.Service) *Service_Specification_Call {
	_c.Call.Return(run)
	return _c
}

// SupportedComponents provides a mock function with no fields
func (_m *Service) SupportedComponents() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportedComponents")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// Service_SupportedComponents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportedComponents'
type Service_SupportedComponents_Call struct {
	*mock.Call
}

// SupportedComponents is a helper method to define mock.On call
func (_e *Service_Expecter) SupportedComponents() *Service_SupportedComponents_Call {
	return &Service_SupportedComponents_Call{Call: _e.mock.On("SupportedComponents")}
}

func (_c *Service_SupportedComponents_Call) Run(run func()) *Service_SupportedComponents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_SupportedComponents_Call) Return(_a0 []string) *Service_SupportedComponents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SupportedComponents_Call) RunAndReturn(run func() []string) *Service_SupportedComponents_Call {
	_c.Call.Return(run)
	return _c
}

// SupportedDurations provides a mock function with no fields
func (_m *Service) SupportedDurations() []int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportedDurations")
	}

	var r0 []int
	if rf, ok := ret.Get(0).(func() []int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	return r0
}

// Service_SupportedDurations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportedDurations'
type Service_SupportedDurations_Call struct {
	*mock.Call
}

// SupportedDurations is a helper method to define mock.On call
func (_e *Service_Expecter) SupportedDurations() *Service_SupportedDurations_Call {
	return &Service_SupportedDurations_Call{Call: _e.mock.On("SupportedDurations")}
}

func (_c *Service_SupportedDurations_Call) Run(run func()) *Service_SupportedDurations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_SupportedDurations_Call) Return(_a0 []int) *Service_SupportedDurations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SupportedDurations_Call) RunAndReturn(run func() []int) *Service_SupportedDurations_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function with no fields
func (_m *Service) Topic() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Service_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type Service_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *Service_Expecter) Topic() *Service_Topic_Call {
	return &Service_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *Service_Topic_Call) Run(run func()) *Service_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Topic_Call) Return(_a0 string) *Service_Topic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Topic_Call) RunAndReturn(run func() string) *Service_Topic_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
