// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedfanctrl

import mock "github.com/stretchr/testify/mock"

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// FanCtrlModeReport provides a mock function with no fields
func (_m *Controller) FanCtrlModeReport() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FanCtrlModeReport")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_FanCtrlModeReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FanCtrlModeReport'
type Controller_FanCtrlModeReport_Call struct {
	*mock.Call
}

// FanCtrlModeReport is a helper method to define mock.On call
func (_e *Controller_Expecter) FanCtrlModeReport() *Controller_FanCtrlModeReport_Call {
	return &Controller_FanCtrlModeReport_Call{Call: _e.mock.On("FanCtrlModeReport")}
}

func (_c *Controller_FanCtrlModeReport_Call) Run(run func()) *Controller_FanCtrlModeReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_FanCtrlModeReport_Call) Return(_a0 string, _a1 error) *Controller_FanCtrlModeReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_FanCtrlModeReport_Call) RunAndReturn(run func() (string, error)) *Controller_FanCtrlModeReport_Call {
	_c.Call.Return(run)
	return _c
}

// SetFanCtrlMode provides a mock function with given fields: mode
func (_m *Controller) SetFanCtrlMode(mode string) error {
	ret := _m.Called(mode)

	if len(ret) == 0 {
		panic("no return value specified for SetFanCtrlMode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(mode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_SetFanCtrlMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFanCtrlMode'
type Controller_SetFanCtrlMode_Call struct {
	*mock.Call
}

// SetFanCtrlMode is a helper method to define mock.On call
//   - mode string
func (_e *Controller_Expecter) SetFanCtrlMode(mode interface{}) *Controller_SetFanCtrlMode_Call {
	return &Controller_SetFanCtrlMode_Call{Call: _e.mock.On("SetFanCtrlMode", mode)}
}

func (_c *Controller_SetFanCtrlMode_Call) Run(run func(mode string)) *Controller_SetFanCtrlMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Controller_SetFanCtrlMode_Call) Return(_a0 error) *Controller_SetFanCtrlMode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_SetFanCtrlMode_Call) RunAndReturn(run func(string) error) *Controller_SetFanCtrlMode_Call {
	_c.Call.Return(run)
	return _c
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
