// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedoutlvlswitch

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// LevelSwitchLevelReport provides a mock function with no fields
func (_m *Controller) LevelSwitchLevelReport() (int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LevelSwitchLevelReport")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_LevelSwitchLevelReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LevelSwitchLevelReport'
type Controller_LevelSwitchLevelReport_Call struct {
	*mock.Call
}

// LevelSwitchLevelReport is a helper method to define mock.On call
func (_e *Controller_Expecter) LevelSwitchLevelReport() *Controller_LevelSwitchLevelReport_Call {
	return &Controller_LevelSwitchLevelReport_Call{Call: _e.mock.On("LevelSwitchLevelReport")}
}

func (_c *Controller_LevelSwitchLevelReport_Call) Run(run func()) *Controller_LevelSwitchLevelReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_LevelSwitchLevelReport_Call) Return(_a0 int, _a1 error) *Controller_LevelSwitchLevelReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_LevelSwitchLevelReport_Call) RunAndReturn(run func() (int, error)) *Controller_LevelSwitchLevelReport_Call {
	_c.Call.Return(run)
	return _c
}

// SetLevelSwitchBinaryState provides a mock function with given fields: _a0
func (_m *Controller) SetLevelSwitchBinaryState(_a0 bool) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetLevelSwitchBinaryState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_SetLevelSwitchBinaryState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLevelSwitchBinaryState'
type Controller_SetLevelSwitchBinaryState_Call struct {
	*mock.Call
}

// SetLevelSwitchBinaryState is a helper method to define mock.On call
//   - _a0 bool
func (_e *Controller_Expecter) SetLevelSwitchBinaryState(_a0 any) *Controller_SetLevelSwitchBinaryState_Call {
	return &Controller_SetLevelSwitchBinaryState_Call{Call: _e.mock.On("SetLevelSwitchBinaryState", _a0)}
}

func (_c *Controller_SetLevelSwitchBinaryState_Call) Run(run func(_a0 bool)) *Controller_SetLevelSwitchBinaryState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *Controller_SetLevelSwitchBinaryState_Call) Return(_a0 error) *Controller_SetLevelSwitchBinaryState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_SetLevelSwitchBinaryState_Call) RunAndReturn(run func(bool) error) *Controller_SetLevelSwitchBinaryState_Call {
	_c.Call.Return(run)
	return _c
}

// SetLevelSwitchLevel provides a mock function with given fields: value, duration
func (_m *Controller) SetLevelSwitchLevel(value int, duration time.Duration) error {
	ret := _m.Called(value, duration)

	if len(ret) == 0 {
		panic("no return value specified for SetLevelSwitchLevel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, time.Duration) error); ok {
		r0 = rf(value, duration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_SetLevelSwitchLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLevelSwitchLevel'
type Controller_SetLevelSwitchLevel_Call struct {
	*mock.Call
}

// SetLevelSwitchLevel is a helper method to define mock.On call
//   - value int
//   - duration time.Duration
func (_e *Controller_Expecter) SetLevelSwitchLevel(value any, duration any) *Controller_SetLevelSwitchLevel_Call {
	return &Controller_SetLevelSwitchLevel_Call{Call: _e.mock.On("SetLevelSwitchLevel", value, duration)}
}

func (_c *Controller_SetLevelSwitchLevel_Call) Run(run func(value int, duration time.Duration)) *Controller_SetLevelSwitchLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(time.Duration))
	})
	return _c
}

func (_c *Controller_SetLevelSwitchLevel_Call) Return(_a0 error) *Controller_SetLevelSwitchLevel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_SetLevelSwitchLevel_Call) RunAndReturn(run func(int, time.Duration) error) *Controller_SetLevelSwitchLevel_Call {
	_c.Call.Return(run)
	return _c
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
