// Code generated by mockery v2.35.3. DO NOT EDIT.

package mockedoutlvlswitch

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// LevelSwitchBinaryStateReport provides a mock function with given fields:
func (_m *Controller) LevelSwitchBinaryStateReport() (bool, error) {
	ret := _m.Called()

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LevelSwitchLevelReport provides a mock function with given fields:
func (_m *Controller) LevelSwitchLevelReport() (int64, error) {
	ret := _m.Called()

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetLevelSwitchBinaryState provides a mock function with given fields: _a0
func (_m *Controller) SetLevelSwitchBinaryState(_a0 bool) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetLevelSwitchLevel provides a mock function with given fields: value, duration
func (_m *Controller) SetLevelSwitchLevel(value int64, duration time.Duration) error {
	ret := _m.Called(value, duration)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, time.Duration) error); ok {
		r0 = rf(value, duration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
