// Code generated by mockery v2.36.1. DO NOT EDIT.

package mockedoutlvlswitch

import (
	outlvlswitch "github.com/futurehomeno/cliffhanger/adapter/service/outlvlswitch"
	mock "github.com/stretchr/testify/mock"
)

// LevelTransitionController is an autogenerated mock type for the LevelTransitionController type
type LevelTransitionController struct {
	mock.Mock
}

// StartLevelTransition provides a mock function with given fields: _a0, _a1
func (_m *LevelTransitionController) StartLevelTransition(_a0 string, _a1 outlvlswitch.LevelTransitionParams) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, outlvlswitch.LevelTransitionParams) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StopLevelTransition provides a mock function with given fields:
func (_m *LevelTransitionController) StopLevelTransition() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLevelTransitionController creates a new instance of LevelTransitionController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLevelTransitionController(t interface {
	mock.TestingT
	Cleanup(func())
}) *LevelTransitionController {
	mock := &LevelTransitionController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
