// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockedprime

import (
	prime "github.com/futurehomeno/cliffhanger/prime"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// ChangeMode provides a mock function with given fields: mode
func (_m *Client) ChangeMode(mode string) (*prime.Response, error) {
	ret := _m.Called(mode)

	if len(ret) == 0 {
		panic("no return value specified for ChangeMode")
	}

	var r0 *prime.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*prime.Response, error)); ok {
		return rf(mode)
	}
	if rf, ok := ret.Get(0).(func(string) *prime.Response); ok {
		r0 = rf(mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*prime.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(mode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ChangeMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeMode'
type Client_ChangeMode_Call struct {
	*mock.Call
}

// ChangeMode is a helper method to define mock.On call
//   - mode string
func (_e *Client_Expecter) ChangeMode(mode interface{}) *Client_ChangeMode_Call {
	return &Client_ChangeMode_Call{Call: _e.mock.On("ChangeMode", mode)}
}

func (_c *Client_ChangeMode_Call) Run(run func(mode string)) *Client_ChangeMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Client_ChangeMode_Call) Return(_a0 *prime.Response, _a1 error) *Client_ChangeMode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ChangeMode_Call) RunAndReturn(run func(string) (*prime.Response, error)) *Client_ChangeMode_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *Client) GetAll() (*prime.ComponentSet, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *prime.ComponentSet
	var r1 error
	if rf, ok := ret.Get(0).(func() (*prime.ComponentSet, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *prime.ComponentSet); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*prime.ComponentSet)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type Client_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *Client_Expecter) GetAll() *Client_GetAll_Call {
	return &Client_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *Client_GetAll_Call) Run(run func()) *Client_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_GetAll_Call) Return(_a0 *prime.ComponentSet, _a1 error) *Client_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetAll_Call) RunAndReturn(run func() (*prime.ComponentSet, error)) *Client_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAreas provides a mock function with no fields
func (_m *Client) GetAreas() (prime.Areas, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAreas")
	}

	var r0 prime.Areas
	var r1 error
	if rf, ok := ret.Get(0).(func() (prime.Areas, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() prime.Areas); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(prime.Areas)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetAreas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAreas'
type Client_GetAreas_Call struct {
	*mock.Call
}

// GetAreas is a helper method to define mock.On call
func (_e *Client_Expecter) GetAreas() *Client_GetAreas_Call {
	return &Client_GetAreas_Call{Call: _e.mock.On("GetAreas")}
}

func (_c *Client_GetAreas_Call) Run(run func()) *Client_GetAreas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_GetAreas_Call) Return(_a0 prime.Areas, _a1 error) *Client_GetAreas_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetAreas_Call) RunAndReturn(run func() (prime.Areas, error)) *Client_GetAreas_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponents provides a mock function with given fields: components
func (_m *Client) GetComponents(components ...string) (*prime.ComponentSet, error) {
	_va := make([]interface{}, len(components))
	for _i := range components {
		_va[_i] = components[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetComponents")
	}

	var r0 *prime.ComponentSet
	var r1 error
	if rf, ok := ret.Get(0).(func(...string) (*prime.ComponentSet, error)); ok {
		return rf(components...)
	}
	if rf, ok := ret.Get(0).(func(...string) *prime.ComponentSet); ok {
		r0 = rf(components...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*prime.ComponentSet)
		}
	}

	if rf, ok := ret.Get(1).(func(...string) error); ok {
		r1 = rf(components...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetComponents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponents'
type Client_GetComponents_Call struct {
	*mock.Call
}

// GetComponents is a helper method to define mock.On call
//   - components ...string
func (_e *Client_Expecter) GetComponents(components ...interface{}) *Client_GetComponents_Call {
	return &Client_GetComponents_Call{Call: _e.mock.On("GetComponents",
		append([]interface{}{}, components...)...)}
}

func (_c *Client_GetComponents_Call) Run(run func(components ...string)) *Client_GetComponents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Client_GetComponents_Call) Return(_a0 *prime.ComponentSet, _a1 error) *Client_GetComponents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetComponents_Call) RunAndReturn(run func(...string) (*prime.ComponentSet, error)) *Client_GetComponents_Call {
	_c.Call.Return(run)
	return _c
}

// GetDevices provides a mock function with no fields
func (_m *Client) GetDevices() (prime.Devices, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDevices")
	}

	var r0 prime.Devices
	var r1 error
	if rf, ok := ret.Get(0).(func() (prime.Devices, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() prime.Devices); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(prime.Devices)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDevices'
type Client_GetDevices_Call struct {
	*mock.Call
}

// GetDevices is a helper method to define mock.On call
func (_e *Client_Expecter) GetDevices() *Client_GetDevices_Call {
	return &Client_GetDevices_Call{Call: _e.mock.On("GetDevices")}
}

func (_c *Client_GetDevices_Call) Run(run func()) *Client_GetDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_GetDevices_Call) Return(_a0 prime.Devices, _a1 error) *Client_GetDevices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetDevices_Call) RunAndReturn(run func() (prime.Devices, error)) *Client_GetDevices_Call {
	_c.Call.Return(run)
	return _c
}

// GetHouse provides a mock function with no fields
func (_m *Client) GetHouse() (*prime.House, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHouse")
	}

	var r0 *prime.House
	var r1 error
	if rf, ok := ret.Get(0).(func() (*prime.House, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *prime.House); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*prime.House)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetHouse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHouse'
type Client_GetHouse_Call struct {
	*mock.Call
}

// GetHouse is a helper method to define mock.On call
func (_e *Client_Expecter) GetHouse() *Client_GetHouse_Call {
	return &Client_GetHouse_Call{Call: _e.mock.On("GetHouse")}
}

func (_c *Client_GetHouse_Call) Run(run func()) *Client_GetHouse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_GetHouse_Call) Return(_a0 *prime.House, _a1 error) *Client_GetHouse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetHouse_Call) RunAndReturn(run func() (*prime.House, error)) *Client_GetHouse_Call {
	_c.Call.Return(run)
	return _c
}

// GetHub provides a mock function with no fields
func (_m *Client) GetHub() (*prime.Hub, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHub")
	}

	var r0 *prime.Hub
	var r1 error
	if rf, ok := ret.Get(0).(func() (*prime.Hub, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *prime.Hub); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*prime.Hub)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetHub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHub'
type Client_GetHub_Call struct {
	*mock.Call
}

// GetHub is a helper method to define mock.On call
func (_e *Client_Expecter) GetHub() *Client_GetHub_Call {
	return &Client_GetHub_Call{Call: _e.mock.On("GetHub")}
}

func (_c *Client_GetHub_Call) Run(run func()) *Client_GetHub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_GetHub_Call) Return(_a0 *prime.Hub, _a1 error) *Client_GetHub_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetHub_Call) RunAndReturn(run func() (*prime.Hub, error)) *Client_GetHub_Call {
	_c.Call.Return(run)
	return _c
}

// GetModes provides a mock function with no fields
func (_m *Client) GetModes() (prime.Modes, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetModes")
	}

	var r0 prime.Modes
	var r1 error
	if rf, ok := ret.Get(0).(func() (prime.Modes, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() prime.Modes); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(prime.Modes)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetModes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModes'
type Client_GetModes_Call struct {
	*mock.Call
}

// GetModes is a helper method to define mock.On call
func (_e *Client_Expecter) GetModes() *Client_GetModes_Call {
	return &Client_GetModes_Call{Call: _e.mock.On("GetModes")}
}

func (_c *Client_GetModes_Call) Run(run func()) *Client_GetModes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_GetModes_Call) Return(_a0 prime.Modes, _a1 error) *Client_GetModes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetModes_Call) RunAndReturn(run func() (prime.Modes, error)) *Client_GetModes_Call {
	_c.Call.Return(run)
	return _c
}

// GetRooms provides a mock function with no fields
func (_m *Client) GetRooms() (prime.Rooms, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRooms")
	}

	var r0 prime.Rooms
	var r1 error
	if rf, ok := ret.Get(0).(func() (prime.Rooms, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() prime.Rooms); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(prime.Rooms)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRooms'
type Client_GetRooms_Call struct {
	*mock.Call
}

// GetRooms is a helper method to define mock.On call
func (_e *Client_Expecter) GetRooms() *Client_GetRooms_Call {
	return &Client_GetRooms_Call{Call: _e.mock.On("GetRooms")}
}

func (_c *Client_GetRooms_Call) Run(run func()) *Client_GetRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_GetRooms_Call) Return(_a0 prime.Rooms, _a1 error) *Client_GetRooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetRooms_Call) RunAndReturn(run func() (prime.Rooms, error)) *Client_GetRooms_Call {
	_c.Call.Return(run)
	return _c
}

// GetShortcuts provides a mock function with no fields
func (_m *Client) GetShortcuts() (prime.Shortcuts, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetShortcuts")
	}

	var r0 prime.Shortcuts
	var r1 error
	if rf, ok := ret.Get(0).(func() (prime.Shortcuts, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() prime.Shortcuts); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(prime.Shortcuts)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetShortcuts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShortcuts'
type Client_GetShortcuts_Call struct {
	*mock.Call
}

// GetShortcuts is a helper method to define mock.On call
func (_e *Client_Expecter) GetShortcuts() *Client_GetShortcuts_Call {
	return &Client_GetShortcuts_Call{Call: _e.mock.On("GetShortcuts")}
}

func (_c *Client_GetShortcuts_Call) Run(run func()) *Client_GetShortcuts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_GetShortcuts_Call) Return(_a0 prime.Shortcuts, _a1 error) *Client_GetShortcuts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetShortcuts_Call) RunAndReturn(run func() (prime.Shortcuts, error)) *Client_GetShortcuts_Call {
	_c.Call.Return(run)
	return _c
}

// GetThings provides a mock function with no fields
func (_m *Client) GetThings() (prime.Things, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetThings")
	}

	var r0 prime.Things
	var r1 error
	if rf, ok := ret.Get(0).(func() (prime.Things, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() prime.Things); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(prime.Things)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetThings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetThings'
type Client_GetThings_Call struct {
	*mock.Call
}

// GetThings is a helper method to define mock.On call
func (_e *Client_Expecter) GetThings() *Client_GetThings_Call {
	return &Client_GetThings_Call{Call: _e.mock.On("GetThings")}
}

func (_c *Client_GetThings_Call) Run(run func()) *Client_GetThings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_GetThings_Call) Return(_a0 prime.Things, _a1 error) *Client_GetThings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetThings_Call) RunAndReturn(run func() (prime.Things, error)) *Client_GetThings_Call {
	_c.Call.Return(run)
	return _c
}

// GetTimers provides a mock function with no fields
func (_m *Client) GetTimers() (prime.Timers, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTimers")
	}

	var r0 prime.Timers
	var r1 error
	if rf, ok := ret.Get(0).(func() (prime.Timers, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() prime.Timers); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(prime.Timers)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetTimers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimers'
type Client_GetTimers_Call struct {
	*mock.Call
}

// GetTimers is a helper method to define mock.On call
func (_e *Client_Expecter) GetTimers() *Client_GetTimers_Call {
	return &Client_GetTimers_Call{Call: _e.mock.On("GetTimers")}
}

func (_c *Client_GetTimers_Call) Run(run func()) *Client_GetTimers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_GetTimers_Call) Return(_a0 prime.Timers, _a1 error) *Client_GetTimers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetTimers_Call) RunAndReturn(run func() (prime.Timers, error)) *Client_GetTimers_Call {
	_c.Call.Return(run)
	return _c
}

// GetVinculumServices provides a mock function with no fields
func (_m *Client) GetVinculumServices() (*prime.VinculumServices, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVinculumServices")
	}

	var r0 *prime.VinculumServices
	var r1 error
	if rf, ok := ret.Get(0).(func() (*prime.VinculumServices, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *prime.VinculumServices); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*prime.VinculumServices)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetVinculumServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVinculumServices'
type Client_GetVinculumServices_Call struct {
	*mock.Call
}

// GetVinculumServices is a helper method to define mock.On call
func (_e *Client_Expecter) GetVinculumServices() *Client_GetVinculumServices_Call {
	return &Client_GetVinculumServices_Call{Call: _e.mock.On("GetVinculumServices")}
}

func (_c *Client_GetVinculumServices_Call) Run(run func()) *Client_GetVinculumServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_GetVinculumServices_Call) Return(_a0 *prime.VinculumServices, _a1 error) *Client_GetVinculumServices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetVinculumServices_Call) RunAndReturn(run func() (*prime.VinculumServices, error)) *Client_GetVinculumServices_Call {
	_c.Call.Return(run)
	return _c
}

// RunShortcut provides a mock function with given fields: shortcutID
func (_m *Client) RunShortcut(shortcutID int) (*prime.Response, error) {
	ret := _m.Called(shortcutID)

	if len(ret) == 0 {
		panic("no return value specified for RunShortcut")
	}

	var r0 *prime.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*prime.Response, error)); ok {
		return rf(shortcutID)
	}
	if rf, ok := ret.Get(0).(func(int) *prime.Response); ok {
		r0 = rf(shortcutID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*prime.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(shortcutID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_RunShortcut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunShortcut'
type Client_RunShortcut_Call struct {
	*mock.Call
}

// RunShortcut is a helper method to define mock.On call
//   - shortcutID int
func (_e *Client_Expecter) RunShortcut(shortcutID interface{}) *Client_RunShortcut_Call {
	return &Client_RunShortcut_Call{Call: _e.mock.On("RunShortcut", shortcutID)}
}

func (_c *Client_RunShortcut_Call) Run(run func(shortcutID int)) *Client_RunShortcut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *Client_RunShortcut_Call) Return(_a0 *prime.Response, _a1 error) *Client_RunShortcut_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_RunShortcut_Call) RunAndReturn(run func(int) (*prime.Response, error)) *Client_RunShortcut_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function with no fields
func (_m *Client) State() (*prime.State, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 *prime.State
	var r1 error
	if rf, ok := ret.Get(0).(func() (*prime.State, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *prime.State); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*prime.State)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type Client_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *Client_Expecter) State() *Client_State_Call {
	return &Client_State_Call{Call: _e.mock.On("State")}
}

func (_c *Client_State_Call) Run(run func()) *Client_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_State_Call) Return(_a0 *prime.State, _a1 error) *Client_State_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_State_Call) RunAndReturn(run func() (*prime.State, error)) *Client_State_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
