// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedprime

import (
	fimpgo "github.com/futurehomeno/fimpgo"
	mock "github.com/stretchr/testify/mock"
)

// SyncClient is an autogenerated mock type for the SyncClient type
type SyncClient struct {
	mock.Mock
}

type SyncClient_Expecter struct {
	mock *mock.Mock
}

func (_m *SyncClient) EXPECT() *SyncClient_Expecter {
	return &SyncClient_Expecter{mock: &_m.Mock}
}

// SendReqRespFimp provides a mock function with given fields: cmdTopic, responseTopic, reqMsg, timeout, autoSubscribe
func (_m *SyncClient) SendReqRespFimp(cmdTopic string, responseTopic string, reqMsg *fimpgo.FimpMessage, timeout int, autoSubscribe bool) (*fimpgo.FimpMessage, error) {
	ret := _m.Called(cmdTopic, responseTopic, reqMsg, timeout, autoSubscribe)

	if len(ret) == 0 {
		panic("no return value specified for SendReqRespFimp")
	}

	var r0 *fimpgo.FimpMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, *fimpgo.FimpMessage, int, bool) (*fimpgo.FimpMessage, error)); ok {
		return rf(cmdTopic, responseTopic, reqMsg, timeout, autoSubscribe)
	}
	if rf, ok := ret.Get(0).(func(string, string, *fimpgo.FimpMessage, int, bool) *fimpgo.FimpMessage); ok {
		r0 = rf(cmdTopic, responseTopic, reqMsg, timeout, autoSubscribe)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fimpgo.FimpMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, *fimpgo.FimpMessage, int, bool) error); ok {
		r1 = rf(cmdTopic, responseTopic, reqMsg, timeout, autoSubscribe)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SyncClient_SendReqRespFimp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendReqRespFimp'
type SyncClient_SendReqRespFimp_Call struct {
	*mock.Call
}

// SendReqRespFimp is a helper method to define mock.On call
//   - cmdTopic string
//   - responseTopic string
//   - reqMsg *fimpgo.FimpMessage
//   - timeout int
//   - autoSubscribe bool
func (_e *SyncClient_Expecter) SendReqRespFimp(cmdTopic interface{}, responseTopic interface{}, reqMsg interface{}, timeout interface{}, autoSubscribe interface{}) *SyncClient_SendReqRespFimp_Call {
	return &SyncClient_SendReqRespFimp_Call{Call: _e.mock.On("SendReqRespFimp", cmdTopic, responseTopic, reqMsg, timeout, autoSubscribe)}
}

func (_c *SyncClient_SendReqRespFimp_Call) Run(run func(cmdTopic string, responseTopic string, reqMsg *fimpgo.FimpMessage, timeout int, autoSubscribe bool)) *SyncClient_SendReqRespFimp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(*fimpgo.FimpMessage), args[3].(int), args[4].(bool))
	})
	return _c
}

func (_c *SyncClient_SendReqRespFimp_Call) Return(_a0 *fimpgo.FimpMessage, _a1 error) *SyncClient_SendReqRespFimp_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SyncClient_SendReqRespFimp_Call) RunAndReturn(run func(string, string, *fimpgo.FimpMessage, int, bool) (*fimpgo.FimpMessage, error)) *SyncClient_SendReqRespFimp_Call {
	_c.Call.Return(run)
	return _c
}

// NewSyncClient creates a new instance of SyncClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSyncClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SyncClient {
	mock := &SyncClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
