// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedparameters

import (
	parameters "github.com/futurehomeno/cliffhanger/adapter/service/parameters"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// GetParameter provides a mock function with given fields: id
func (_m *Controller) GetParameter(id string) (*parameters.Parameter, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetParameter")
	}

	var r0 *parameters.Parameter
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*parameters.Parameter, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *parameters.Parameter); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*parameters.Parameter)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_GetParameter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParameter'
type Controller_GetParameter_Call struct {
	*mock.Call
}

// GetParameter is a helper method to define mock.On call
//   - id string
func (_e *Controller_Expecter) GetParameter(id any) *Controller_GetParameter_Call {
	return &Controller_GetParameter_Call{Call: _e.mock.On("GetParameter", id)}
}

func (_c *Controller_GetParameter_Call) Run(run func(id string)) *Controller_GetParameter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Controller_GetParameter_Call) Return(_a0 *parameters.Parameter, _a1 error) *Controller_GetParameter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_GetParameter_Call) RunAndReturn(run func(string) (*parameters.Parameter, error)) *Controller_GetParameter_Call {
	_c.Call.Return(run)
	return _c
}

// GetParameterSpecifications provides a mock function with no fields
func (_m *Controller) GetParameterSpecifications() ([]*parameters.ParameterSpecification, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetParameterSpecifications")
	}

	var r0 []*parameters.ParameterSpecification
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*parameters.ParameterSpecification, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*parameters.ParameterSpecification); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*parameters.ParameterSpecification)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_GetParameterSpecifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParameterSpecifications'
type Controller_GetParameterSpecifications_Call struct {
	*mock.Call
}

// GetParameterSpecifications is a helper method to define mock.On call
func (_e *Controller_Expecter) GetParameterSpecifications() *Controller_GetParameterSpecifications_Call {
	return &Controller_GetParameterSpecifications_Call{Call: _e.mock.On("GetParameterSpecifications")}
}

func (_c *Controller_GetParameterSpecifications_Call) Run(run func()) *Controller_GetParameterSpecifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_GetParameterSpecifications_Call) Return(_a0 []*parameters.ParameterSpecification, _a1 error) *Controller_GetParameterSpecifications_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_GetParameterSpecifications_Call) RunAndReturn(run func() ([]*parameters.ParameterSpecification, error)) *Controller_GetParameterSpecifications_Call {
	_c.Call.Return(run)
	return _c
}

// SetParameter provides a mock function with given fields: p
func (_m *Controller) SetParameter(p *parameters.Parameter) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for SetParameter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*parameters.Parameter) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_SetParameter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetParameter'
type Controller_SetParameter_Call struct {
	*mock.Call
}

// SetParameter is a helper method to define mock.On call
//   - p *parameters.Parameter
func (_e *Controller_Expecter) SetParameter(p any) *Controller_SetParameter_Call {
	return &Controller_SetParameter_Call{Call: _e.mock.On("SetParameter", p)}
}

func (_c *Controller_SetParameter_Call) Run(run func(p *parameters.Parameter)) *Controller_SetParameter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*parameters.Parameter))
	})
	return _c
}

func (_c *Controller_SetParameter_Call) Return(_a0 error) *Controller_SetParameter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_SetParameter_Call) RunAndReturn(run func(*parameters.Parameter) error) *Controller_SetParameter_Call {
	_c.Call.Return(run)
	return _c
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
