// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedparameters

import (
	adapter "github.com/futurehomeno/cliffhanger/adapter"
	parameters "github.com/futurehomeno/cliffhanger/adapter/service/parameters"
	fimpgo "github.com/futurehomeno/fimpgo"
	fimptype "github.com/futurehomeno/fimpgo/fimptype"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with no fields
func (_m *Service) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Service_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Service_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Service_Expecter) Name() *Service_Name_Call {
	return &Service_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Service_Name_Call) Run(run func()) *Service_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Name_Call) Return(_a0 string) *Service_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Name_Call) RunAndReturn(run func() string) *Service_Name_Call {
	_c.Call.Return(run)
	return _c
}

// PublishEvent provides a mock function with given fields: event
func (_m *Service) PublishEvent(event adapter.ServiceEvent) {
	_m.Called(event)
}

// Service_PublishEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishEvent'
type Service_PublishEvent_Call struct {
	*mock.Call
}

// PublishEvent is a helper method to define mock.On call
//   - event adapter.ServiceEvent
func (_e *Service_Expecter) PublishEvent(event interface{}) *Service_PublishEvent_Call {
	return &Service_PublishEvent_Call{Call: _e.mock.On("PublishEvent", event)}
}

func (_c *Service_PublishEvent_Call) Run(run func(event adapter.ServiceEvent)) *Service_PublishEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(adapter.ServiceEvent))
	})
	return _c
}

func (_c *Service_PublishEvent_Call) Return() *Service_PublishEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *Service_PublishEvent_Call) RunAndReturn(run func(adapter.ServiceEvent)) *Service_PublishEvent_Call {
	_c.Run(run)
	return _c
}

// SendMessage provides a mock function with given fields: message
func (_m *Service) SendMessage(message *fimpgo.FimpMessage) error {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*fimpgo.FimpMessage) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type Service_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - message *fimpgo.FimpMessage
func (_e *Service_Expecter) SendMessage(message interface{}) *Service_SendMessage_Call {
	return &Service_SendMessage_Call{Call: _e.mock.On("SendMessage", message)}
}

func (_c *Service_SendMessage_Call) Run(run func(message *fimpgo.FimpMessage)) *Service_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fimpgo.FimpMessage))
	})
	return _c
}

func (_c *Service_SendMessage_Call) Return(_a0 error) *Service_SendMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SendMessage_Call) RunAndReturn(run func(*fimpgo.FimpMessage) error) *Service_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendParameterReport provides a mock function with given fields: id, force
func (_m *Service) SendParameterReport(id string, force bool) (bool, error) {
	ret := _m.Called(id, force)

	if len(ret) == 0 {
		panic("no return value specified for SendParameterReport")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, bool) (bool, error)); ok {
		return rf(id, force)
	}
	if rf, ok := ret.Get(0).(func(string, bool) bool); ok {
		r0 = rf(id, force)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = rf(id, force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_SendParameterReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendParameterReport'
type Service_SendParameterReport_Call struct {
	*mock.Call
}

// SendParameterReport is a helper method to define mock.On call
//   - id string
//   - force bool
func (_e *Service_Expecter) SendParameterReport(id interface{}, force interface{}) *Service_SendParameterReport_Call {
	return &Service_SendParameterReport_Call{Call: _e.mock.On("SendParameterReport", id, force)}
}

func (_c *Service_SendParameterReport_Call) Run(run func(id string, force bool)) *Service_SendParameterReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *Service_SendParameterReport_Call) Return(_a0 bool, _a1 error) *Service_SendParameterReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_SendParameterReport_Call) RunAndReturn(run func(string, bool) (bool, error)) *Service_SendParameterReport_Call {
	_c.Call.Return(run)
	return _c
}

// SendSupportedParamsReport provides a mock function with given fields: force
func (_m *Service) SendSupportedParamsReport(force bool) (bool, error) {
	ret := _m.Called(force)

	if len(ret) == 0 {
		panic("no return value specified for SendSupportedParamsReport")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(bool) (bool, error)); ok {
		return rf(force)
	}
	if rf, ok := ret.Get(0).(func(bool) bool); ok {
		r0 = rf(force)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(bool) error); ok {
		r1 = rf(force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_SendSupportedParamsReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendSupportedParamsReport'
type Service_SendSupportedParamsReport_Call struct {
	*mock.Call
}

// SendSupportedParamsReport is a helper method to define mock.On call
//   - force bool
func (_e *Service_Expecter) SendSupportedParamsReport(force interface{}) *Service_SendSupportedParamsReport_Call {
	return &Service_SendSupportedParamsReport_Call{Call: _e.mock.On("SendSupportedParamsReport", force)}
}

func (_c *Service_SendSupportedParamsReport_Call) Run(run func(force bool)) *Service_SendSupportedParamsReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *Service_SendSupportedParamsReport_Call) Return(_a0 bool, _a1 error) *Service_SendSupportedParamsReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_SendSupportedParamsReport_Call) RunAndReturn(run func(bool) (bool, error)) *Service_SendSupportedParamsReport_Call {
	_c.Call.Return(run)
	return _c
}

// SetParameter provides a mock function with given fields: p
func (_m *Service) SetParameter(p *parameters.Parameter) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for SetParameter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*parameters.Parameter) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_SetParameter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetParameter'
type Service_SetParameter_Call struct {
	*mock.Call
}

// SetParameter is a helper method to define mock.On call
//   - p *parameters.Parameter
func (_e *Service_Expecter) SetParameter(p interface{}) *Service_SetParameter_Call {
	return &Service_SetParameter_Call{Call: _e.mock.On("SetParameter", p)}
}

func (_c *Service_SetParameter_Call) Run(run func(p *parameters.Parameter)) *Service_SetParameter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*parameters.Parameter))
	})
	return _c
}

func (_c *Service_SetParameter_Call) Return(_a0 error) *Service_SetParameter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SetParameter_Call) RunAndReturn(run func(*parameters.Parameter) error) *Service_SetParameter_Call {
	_c.Call.Return(run)
	return _c
}

// Specification provides a mock function with no fields
func (_m *Service) Specification() *fimptype.Service {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Specification")
	}

	var r0 *fimptype.Service
	if rf, ok := ret.Get(0).(func() *fimptype.Service); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fimptype.Service)
		}
	}

	return r0
}

// Service_Specification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Specification'
type Service_Specification_Call struct {
	*mock.Call
}

// Specification is a helper method to define mock.On call
func (_e *Service_Expecter) Specification() *Service_Specification_Call {
	return &Service_Specification_Call{Call: _e.mock.On("Specification")}
}

func (_c *Service_Specification_Call) Run(run func()) *Service_Specification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Specification_Call) Return(_a0 *fimptype.Service) *Service_Specification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Specification_Call) RunAndReturn(run func() *fimptype.Service) *Service_Specification_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function with no fields
func (_m *Service) Topic() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Service_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type Service_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *Service_Expecter) Topic() *Service_Topic_Call {
	return &Service_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *Service_Topic_Call) Run(run func()) *Service_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Topic_Call) Return(_a0 string) *Service_Topic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Topic_Call) RunAndReturn(run func() string) *Service_Topic_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
