// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedbattery

import (
	battery "github.com/futurehomeno/cliffhanger/adapter/service/battery"
	mock "github.com/stretchr/testify/mock"
)

// Reporter is an autogenerated mock type for the Reporter type
type Reporter struct {
	mock.Mock
}

type Reporter_Expecter struct {
	mock *mock.Mock
}

func (_m *Reporter) EXPECT() *Reporter_Expecter {
	return &Reporter_Expecter{mock: &_m.Mock}
}

// BatteryAlarmReport provides a mock function with given fields: event
func (_m *Reporter) BatteryAlarmReport(event string) (*battery.AlarmReport, error) {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for BatteryAlarmReport")
	}

	var r0 *battery.AlarmReport
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*battery.AlarmReport, error)); ok {
		return rf(event)
	}
	if rf, ok := ret.Get(0).(func(string) *battery.AlarmReport); ok {
		r0 = rf(event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*battery.AlarmReport)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reporter_BatteryAlarmReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatteryAlarmReport'
type Reporter_BatteryAlarmReport_Call struct {
	*mock.Call
}

// BatteryAlarmReport is a helper method to define mock.On call
//   - event string
func (_e *Reporter_Expecter) BatteryAlarmReport(event interface{}) *Reporter_BatteryAlarmReport_Call {
	return &Reporter_BatteryAlarmReport_Call{Call: _e.mock.On("BatteryAlarmReport", event)}
}

func (_c *Reporter_BatteryAlarmReport_Call) Run(run func(event string)) *Reporter_BatteryAlarmReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Reporter_BatteryAlarmReport_Call) Return(_a0 *battery.AlarmReport, _a1 error) *Reporter_BatteryAlarmReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Reporter_BatteryAlarmReport_Call) RunAndReturn(run func(string) (*battery.AlarmReport, error)) *Reporter_BatteryAlarmReport_Call {
	_c.Call.Return(run)
	return _c
}

// BatteryLevelReport provides a mock function with no fields
func (_m *Reporter) BatteryLevelReport() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BatteryLevelReport")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reporter_BatteryLevelReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatteryLevelReport'
type Reporter_BatteryLevelReport_Call struct {
	*mock.Call
}

// BatteryLevelReport is a helper method to define mock.On call
func (_e *Reporter_Expecter) BatteryLevelReport() *Reporter_BatteryLevelReport_Call {
	return &Reporter_BatteryLevelReport_Call{Call: _e.mock.On("BatteryLevelReport")}
}

func (_c *Reporter_BatteryLevelReport_Call) Run(run func()) *Reporter_BatteryLevelReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Reporter_BatteryLevelReport_Call) Return(level int64, err error) *Reporter_BatteryLevelReport_Call {
	_c.Call.Return(level, err)
	return _c
}

func (_c *Reporter_BatteryLevelReport_Call) RunAndReturn(run func() (int64, error)) *Reporter_BatteryLevelReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewReporter creates a new instance of Reporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reporter {
	mock := &Reporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
