// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedmediaplayer

import (
	mediaplayer "github.com/futurehomeno/cliffhanger/adapter/service/mediaplayer"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// Metadata provides a mock function with no fields
func (_m *Controller) Metadata() (map[string]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type Controller_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *Controller_Expecter) Metadata() *Controller_Metadata_Call {
	return &Controller_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *Controller_Metadata_Call) Run(run func()) *Controller_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_Metadata_Call) Return(_a0 map[string]string, _a1 error) *Controller_Metadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_Metadata_Call) RunAndReturn(run func() (map[string]string, error)) *Controller_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// Mute provides a mock function with no fields
func (_m *Controller) Mute() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Mute")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_Mute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mute'
type Controller_Mute_Call struct {
	*mock.Call
}

// Mute is a helper method to define mock.On call
func (_e *Controller_Expecter) Mute() *Controller_Mute_Call {
	return &Controller_Mute_Call{Call: _e.mock.On("Mute")}
}

func (_c *Controller_Mute_Call) Run(run func()) *Controller_Mute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_Mute_Call) Return(_a0 bool, _a1 error) *Controller_Mute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_Mute_Call) RunAndReturn(run func() (bool, error)) *Controller_Mute_Call {
	_c.Call.Return(run)
	return _c
}

// Playback provides a mock function with no fields
func (_m *Controller) Playback() (mediaplayer.PlaybackAction, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Playback")
	}

	var r0 mediaplayer.PlaybackAction
	var r1 error
	if rf, ok := ret.Get(0).(func() (mediaplayer.PlaybackAction, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() mediaplayer.PlaybackAction); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(mediaplayer.PlaybackAction)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_Playback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Playback'
type Controller_Playback_Call struct {
	*mock.Call
}

// Playback is a helper method to define mock.On call
func (_e *Controller_Expecter) Playback() *Controller_Playback_Call {
	return &Controller_Playback_Call{Call: _e.mock.On("Playback")}
}

func (_c *Controller_Playback_Call) Run(run func()) *Controller_Playback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_Playback_Call) Return(_a0 mediaplayer.PlaybackAction, _a1 error) *Controller_Playback_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_Playback_Call) RunAndReturn(run func() (mediaplayer.PlaybackAction, error)) *Controller_Playback_Call {
	_c.Call.Return(run)
	return _c
}

// PlaybackMode provides a mock function with no fields
func (_m *Controller) PlaybackMode() (map[string]bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PlaybackMode")
	}

	var r0 map[string]bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]bool); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]bool)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_PlaybackMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaybackMode'
type Controller_PlaybackMode_Call struct {
	*mock.Call
}

// PlaybackMode is a helper method to define mock.On call
func (_e *Controller_Expecter) PlaybackMode() *Controller_PlaybackMode_Call {
	return &Controller_PlaybackMode_Call{Call: _e.mock.On("PlaybackMode")}
}

func (_c *Controller_PlaybackMode_Call) Run(run func()) *Controller_PlaybackMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_PlaybackMode_Call) Return(_a0 map[string]bool, _a1 error) *Controller_PlaybackMode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_PlaybackMode_Call) RunAndReturn(run func() (map[string]bool, error)) *Controller_PlaybackMode_Call {
	_c.Call.Return(run)
	return _c
}

// SetMute provides a mock function with given fields: mute
func (_m *Controller) SetMute(mute bool) error {
	ret := _m.Called(mute)

	if len(ret) == 0 {
		panic("no return value specified for SetMute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(mute)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_SetMute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMute'
type Controller_SetMute_Call struct {
	*mock.Call
}

// SetMute is a helper method to define mock.On call
//   - mute bool
func (_e *Controller_Expecter) SetMute(mute interface{}) *Controller_SetMute_Call {
	return &Controller_SetMute_Call{Call: _e.mock.On("SetMute", mute)}
}

func (_c *Controller_SetMute_Call) Run(run func(mute bool)) *Controller_SetMute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *Controller_SetMute_Call) Return(_a0 error) *Controller_SetMute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_SetMute_Call) RunAndReturn(run func(bool) error) *Controller_SetMute_Call {
	_c.Call.Return(run)
	return _c
}

// SetPlayback provides a mock function with given fields: action
func (_m *Controller) SetPlayback(action mediaplayer.PlaybackAction) error {
	ret := _m.Called(action)

	if len(ret) == 0 {
		panic("no return value specified for SetPlayback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(mediaplayer.PlaybackAction) error); ok {
		r0 = rf(action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_SetPlayback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPlayback'
type Controller_SetPlayback_Call struct {
	*mock.Call
}

// SetPlayback is a helper method to define mock.On call
//   - action mediaplayer.PlaybackAction
func (_e *Controller_Expecter) SetPlayback(action interface{}) *Controller_SetPlayback_Call {
	return &Controller_SetPlayback_Call{Call: _e.mock.On("SetPlayback", action)}
}

func (_c *Controller_SetPlayback_Call) Run(run func(action mediaplayer.PlaybackAction)) *Controller_SetPlayback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(mediaplayer.PlaybackAction))
	})
	return _c
}

func (_c *Controller_SetPlayback_Call) Return(_a0 error) *Controller_SetPlayback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_SetPlayback_Call) RunAndReturn(run func(mediaplayer.PlaybackAction) error) *Controller_SetPlayback_Call {
	_c.Call.Return(run)
	return _c
}

// SetPlaybackMode provides a mock function with given fields: mode
func (_m *Controller) SetPlaybackMode(mode map[string]bool) error {
	ret := _m.Called(mode)

	if len(ret) == 0 {
		panic("no return value specified for SetPlaybackMode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]bool) error); ok {
		r0 = rf(mode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_SetPlaybackMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPlaybackMode'
type Controller_SetPlaybackMode_Call struct {
	*mock.Call
}

// SetPlaybackMode is a helper method to define mock.On call
//   - mode map[string]bool
func (_e *Controller_Expecter) SetPlaybackMode(mode interface{}) *Controller_SetPlaybackMode_Call {
	return &Controller_SetPlaybackMode_Call{Call: _e.mock.On("SetPlaybackMode", mode)}
}

func (_c *Controller_SetPlaybackMode_Call) Run(run func(mode map[string]bool)) *Controller_SetPlaybackMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]bool))
	})
	return _c
}

func (_c *Controller_SetPlaybackMode_Call) Return(_a0 error) *Controller_SetPlaybackMode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_SetPlaybackMode_Call) RunAndReturn(run func(map[string]bool) error) *Controller_SetPlaybackMode_Call {
	_c.Call.Return(run)
	return _c
}

// SetVolume provides a mock function with given fields: level
func (_m *Controller) SetVolume(level int) error {
	ret := _m.Called(level)

	if len(ret) == 0 {
		panic("no return value specified for SetVolume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(level)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_SetVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVolume'
type Controller_SetVolume_Call struct {
	*mock.Call
}

// SetVolume is a helper method to define mock.On call
//   - level int
func (_e *Controller_Expecter) SetVolume(level interface{}) *Controller_SetVolume_Call {
	return &Controller_SetVolume_Call{Call: _e.mock.On("SetVolume", level)}
}

func (_c *Controller_SetVolume_Call) Run(run func(level int)) *Controller_SetVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *Controller_SetVolume_Call) Return(_a0 error) *Controller_SetVolume_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_SetVolume_Call) RunAndReturn(run func(int) error) *Controller_SetVolume_Call {
	_c.Call.Return(run)
	return _c
}

// Volume provides a mock function with no fields
func (_m *Controller) Volume() (int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Volume")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_Volume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Volume'
type Controller_Volume_Call struct {
	*mock.Call
}

// Volume is a helper method to define mock.On call
func (_e *Controller_Expecter) Volume() *Controller_Volume_Call {
	return &Controller_Volume_Call{Call: _e.mock.On("Volume")}
}

func (_c *Controller_Volume_Call) Run(run func()) *Controller_Volume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_Volume_Call) Return(_a0 int, _a1 error) *Controller_Volume_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_Volume_Call) RunAndReturn(run func() (int, error)) *Controller_Volume_Call {
	_c.Call.Return(run)
	return _c
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
