// Code generated by mockery v2.36.0. DO NOT EDIT.

package mockedvirtualmeter

import (
	adapter "github.com/futurehomeno/cliffhanger/adapter"
	mock "github.com/stretchr/testify/mock"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// RegisterThing provides a mock function with given fields: thing, publisher
func (_m *Manager) RegisterThing(thing adapter.Thing, publisher adapter.Publisher) error {
	ret := _m.Called(thing, publisher)

	var r0 error
	if rf, ok := ret.Get(0).(func(adapter.Thing, adapter.Publisher) error); ok {
		r0 = rf(thing, publisher)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithAdapter provides a mock function with given fields: ad
func (_m *Manager) WithAdapter(ad adapter.Adapter) {
	_m.Called(ad)
}

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
