// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedvirtualmeter

import (
	adapter "github.com/futurehomeno/cliffhanger/adapter"
	mock "github.com/stretchr/testify/mock"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

type Manager_Expecter struct {
	mock *mock.Mock
}

func (_m *Manager) EXPECT() *Manager_Expecter {
	return &Manager_Expecter{mock: &_m.Mock}
}

// RegisterThing provides a mock function with given fields: thing, publisher
func (_m *Manager) RegisterThing(thing adapter.Thing, publisher adapter.Publisher) error {
	ret := _m.Called(thing, publisher)

	if len(ret) == 0 {
		panic("no return value specified for RegisterThing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(adapter.Thing, adapter.Publisher) error); ok {
		r0 = rf(thing, publisher)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Manager_RegisterThing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterThing'
type Manager_RegisterThing_Call struct {
	*mock.Call
}

// RegisterThing is a helper method to define mock.On call
//   - thing adapter.Thing
//   - publisher adapter.Publisher
func (_e *Manager_Expecter) RegisterThing(thing interface{}, publisher interface{}) *Manager_RegisterThing_Call {
	return &Manager_RegisterThing_Call{Call: _e.mock.On("RegisterThing", thing, publisher)}
}

func (_c *Manager_RegisterThing_Call) Run(run func(thing adapter.Thing, publisher adapter.Publisher)) *Manager_RegisterThing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(adapter.Thing), args[1].(adapter.Publisher))
	})
	return _c
}

func (_c *Manager_RegisterThing_Call) Return(_a0 error) *Manager_RegisterThing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Manager_RegisterThing_Call) RunAndReturn(run func(adapter.Thing, adapter.Publisher) error) *Manager_RegisterThing_Call {
	_c.Call.Return(run)
	return _c
}

// WithAdapter provides a mock function with given fields: ad
func (_m *Manager) WithAdapter(ad adapter.Adapter) {
	_m.Called(ad)
}

// Manager_WithAdapter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithAdapter'
type Manager_WithAdapter_Call struct {
	*mock.Call
}

// WithAdapter is a helper method to define mock.On call
//   - ad adapter.Adapter
func (_e *Manager_Expecter) WithAdapter(ad interface{}) *Manager_WithAdapter_Call {
	return &Manager_WithAdapter_Call{Call: _e.mock.On("WithAdapter", ad)}
}

func (_c *Manager_WithAdapter_Call) Run(run func(ad adapter.Adapter)) *Manager_WithAdapter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(adapter.Adapter))
	})
	return _c
}

func (_c *Manager_WithAdapter_Call) Return() *Manager_WithAdapter_Call {
	_c.Call.Return()
	return _c
}

func (_c *Manager_WithAdapter_Call) RunAndReturn(run func(adapter.Adapter)) *Manager_WithAdapter_Call {
	_c.Run(run)
	return _c
}

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
