// Code generated by mockery v2.23.0. DO NOT EDIT.

package mockednumericmeter

import mock "github.com/stretchr/testify/mock"

// ExtendedReporter is an autogenerated mock type for the ExtendedReporter type
type ExtendedReporter struct {
	mock.Mock
}

// MeterExtendedReport provides a mock function with given fields: values
func (_m *ExtendedReporter) MeterExtendedReport(values []string) (map[string]float64, error) {
	ret := _m.Called(values)

	var r0 map[string]float64
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) (map[string]float64, error)); ok {
		return rf(values)
	}
	if rf, ok := ret.Get(0).(func([]string) map[string]float64); ok {
		r0 = rf(values)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(values)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewExtendedReporter interface {
	mock.TestingT
	Cleanup(func())
}

// NewExtendedReporter creates a new instance of ExtendedReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExtendedReporter(t mockConstructorTestingTNewExtendedReporter) *ExtendedReporter {
	mock := &ExtendedReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
