// Code generated by mockery v2.33.3. DO NOT EDIT.

package mockednumericmeter

import mock "github.com/stretchr/testify/mock"

// ResettableReporter is an autogenerated mock type for the ResettableReporter type
type ResettableReporter struct {
	mock.Mock
}

// MeterReset provides a mock function with given fields:
func (_m *ResettableReporter) MeterReset() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewResettableReporter creates a new instance of ResettableReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResettableReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResettableReporter {
	mock := &ResettableReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
