// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedota

import (
	ota "github.com/futurehomeno/cliffhanger/adapter/service/ota"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// OTAStatusReport provides a mock function with no fields
func (_m *Controller) OTAStatusReport() (ota.StatusReport, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OTAStatusReport")
	}

	var r0 ota.StatusReport
	var r1 error
	if rf, ok := ret.Get(0).(func() (ota.StatusReport, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() ota.StatusReport); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ota.StatusReport)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_OTAStatusReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OTAStatusReport'
type Controller_OTAStatusReport_Call struct {
	*mock.Call
}

// OTAStatusReport is a helper method to define mock.On call
func (_e *Controller_Expecter) OTAStatusReport() *Controller_OTAStatusReport_Call {
	return &Controller_OTAStatusReport_Call{Call: _e.mock.On("OTAStatusReport")}
}

func (_c *Controller_OTAStatusReport_Call) Run(run func()) *Controller_OTAStatusReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_OTAStatusReport_Call) Return(_a0 ota.StatusReport, _a1 error) *Controller_OTAStatusReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_OTAStatusReport_Call) RunAndReturn(run func() (ota.StatusReport, error)) *Controller_OTAStatusReport_Call {
	_c.Call.Return(run)
	return _c
}

// StartOTAUpdate provides a mock function with given fields: firmwarePath
func (_m *Controller) StartOTAUpdate(firmwarePath string) error {
	ret := _m.Called(firmwarePath)

	if len(ret) == 0 {
		panic("no return value specified for StartOTAUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(firmwarePath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_StartOTAUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartOTAUpdate'
type Controller_StartOTAUpdate_Call struct {
	*mock.Call
}

// StartOTAUpdate is a helper method to define mock.On call
//   - firmwarePath string
func (_e *Controller_Expecter) StartOTAUpdate(firmwarePath any) *Controller_StartOTAUpdate_Call {
	return &Controller_StartOTAUpdate_Call{Call: _e.mock.On("StartOTAUpdate", firmwarePath)}
}

func (_c *Controller_StartOTAUpdate_Call) Run(run func(firmwarePath string)) *Controller_StartOTAUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Controller_StartOTAUpdate_Call) Return(_a0 error) *Controller_StartOTAUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_StartOTAUpdate_Call) RunAndReturn(run func(string) error) *Controller_StartOTAUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
