// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedchargepoint

import (
	types "github.com/futurehomeno/cliffhanger/types"
	mock "github.com/stretchr/testify/mock"
)

// AdjustablePhaseModeController is an autogenerated mock type for the AdjustablePhaseModeController type
type AdjustablePhaseModeController struct {
	mock.Mock
}

type AdjustablePhaseModeController_Expecter struct {
	mock *mock.Mock
}

func (_m *AdjustablePhaseModeController) EXPECT() *AdjustablePhaseModeController_Expecter {
	return &AdjustablePhaseModeController_Expecter{mock: &_m.Mock}
}

// ChargepointPhaseModeReport provides a mock function with no fields
func (_m *AdjustablePhaseModeController) ChargepointPhaseModeReport() (types.PhaseMode, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChargepointPhaseModeReport")
	}

	var r0 types.PhaseMode
	var r1 error
	if rf, ok := ret.Get(0).(func() (types.PhaseMode, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() types.PhaseMode); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.PhaseMode)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdjustablePhaseModeController_ChargepointPhaseModeReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChargepointPhaseModeReport'
type AdjustablePhaseModeController_ChargepointPhaseModeReport_Call struct {
	*mock.Call
}

// ChargepointPhaseModeReport is a helper method to define mock.On call
func (_e *AdjustablePhaseModeController_Expecter) ChargepointPhaseModeReport() *AdjustablePhaseModeController_ChargepointPhaseModeReport_Call {
	return &AdjustablePhaseModeController_ChargepointPhaseModeReport_Call{Call: _e.mock.On("ChargepointPhaseModeReport")}
}

func (_c *AdjustablePhaseModeController_ChargepointPhaseModeReport_Call) Run(run func()) *AdjustablePhaseModeController_ChargepointPhaseModeReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AdjustablePhaseModeController_ChargepointPhaseModeReport_Call) Return(_a0 types.PhaseMode, _a1 error) *AdjustablePhaseModeController_ChargepointPhaseModeReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdjustablePhaseModeController_ChargepointPhaseModeReport_Call) RunAndReturn(run func() (types.PhaseMode, error)) *AdjustablePhaseModeController_ChargepointPhaseModeReport_Call {
	_c.Call.Return(run)
	return _c
}

// SetChargepointPhaseMode provides a mock function with given fields: _a0
func (_m *AdjustablePhaseModeController) SetChargepointPhaseMode(_a0 types.PhaseMode) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetChargepointPhaseMode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.PhaseMode) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AdjustablePhaseModeController_SetChargepointPhaseMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetChargepointPhaseMode'
type AdjustablePhaseModeController_SetChargepointPhaseMode_Call struct {
	*mock.Call
}

// SetChargepointPhaseMode is a helper method to define mock.On call
//   - _a0 types.PhaseMode
func (_e *AdjustablePhaseModeController_Expecter) SetChargepointPhaseMode(_a0 interface{}) *AdjustablePhaseModeController_SetChargepointPhaseMode_Call {
	return &AdjustablePhaseModeController_SetChargepointPhaseMode_Call{Call: _e.mock.On("SetChargepointPhaseMode", _a0)}
}

func (_c *AdjustablePhaseModeController_SetChargepointPhaseMode_Call) Run(run func(_a0 types.PhaseMode)) *AdjustablePhaseModeController_SetChargepointPhaseMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.PhaseMode))
	})
	return _c
}

func (_c *AdjustablePhaseModeController_SetChargepointPhaseMode_Call) Return(_a0 error) *AdjustablePhaseModeController_SetChargepointPhaseMode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AdjustablePhaseModeController_SetChargepointPhaseMode_Call) RunAndReturn(run func(types.PhaseMode) error) *AdjustablePhaseModeController_SetChargepointPhaseMode_Call {
	_c.Call.Return(run)
	return _c
}

// NewAdjustablePhaseModeController creates a new instance of AdjustablePhaseModeController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdjustablePhaseModeController(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdjustablePhaseModeController {
	mock := &AdjustablePhaseModeController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
