// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedchargepoint

import mock "github.com/stretchr/testify/mock"

// AdjustableOfferedCurrentController is an autogenerated mock type for the AdjustableOfferedCurrentController type
type AdjustableOfferedCurrentController struct {
	mock.Mock
}

type AdjustableOfferedCurrentController_Expecter struct {
	mock *mock.Mock
}

func (_m *AdjustableOfferedCurrentController) EXPECT() *AdjustableOfferedCurrentController_Expecter {
	return &AdjustableOfferedCurrentController_Expecter{mock: &_m.Mock}
}

// SetChargepointOfferedCurrent provides a mock function with given fields: _a0
func (_m *AdjustableOfferedCurrentController) SetChargepointOfferedCurrent(_a0 int) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetChargepointOfferedCurrent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AdjustableOfferedCurrentController_SetChargepointOfferedCurrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetChargepointOfferedCurrent'
type AdjustableOfferedCurrentController_SetChargepointOfferedCurrent_Call struct {
	*mock.Call
}

// SetChargepointOfferedCurrent is a helper method to define mock.On call
//   - _a0 int
func (_e *AdjustableOfferedCurrentController_Expecter) SetChargepointOfferedCurrent(_a0 interface{}) *AdjustableOfferedCurrentController_SetChargepointOfferedCurrent_Call {
	return &AdjustableOfferedCurrentController_SetChargepointOfferedCurrent_Call{Call: _e.mock.On("SetChargepointOfferedCurrent", _a0)}
}

func (_c *AdjustableOfferedCurrentController_SetChargepointOfferedCurrent_Call) Run(run func(_a0 int)) *AdjustableOfferedCurrentController_SetChargepointOfferedCurrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *AdjustableOfferedCurrentController_SetChargepointOfferedCurrent_Call) Return(_a0 error) *AdjustableOfferedCurrentController_SetChargepointOfferedCurrent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AdjustableOfferedCurrentController_SetChargepointOfferedCurrent_Call) RunAndReturn(run func(int) error) *AdjustableOfferedCurrentController_SetChargepointOfferedCurrent_Call {
	_c.Call.Return(run)
	return _c
}

// NewAdjustableOfferedCurrentController creates a new instance of AdjustableOfferedCurrentController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdjustableOfferedCurrentController(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdjustableOfferedCurrentController {
	mock := &AdjustableOfferedCurrentController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
