// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedchargepoint

import mock "github.com/stretchr/testify/mock"

// AdjustableMaxCurrentController is an autogenerated mock type for the AdjustableMaxCurrentController type
type AdjustableMaxCurrentController struct {
	mock.Mock
}

type AdjustableMaxCurrentController_Expecter struct {
	mock *mock.Mock
}

func (_m *AdjustableMaxCurrentController) EXPECT() *AdjustableMaxCurrentController_Expecter {
	return &AdjustableMaxCurrentController_Expecter{mock: &_m.Mock}
}

// ChargepointMaxCurrentReport provides a mock function with no fields
func (_m *AdjustableMaxCurrentController) ChargepointMaxCurrentReport() (int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChargepointMaxCurrentReport")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdjustableMaxCurrentController_ChargepointMaxCurrentReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChargepointMaxCurrentReport'
type AdjustableMaxCurrentController_ChargepointMaxCurrentReport_Call struct {
	*mock.Call
}

// ChargepointMaxCurrentReport is a helper method to define mock.On call
func (_e *AdjustableMaxCurrentController_Expecter) ChargepointMaxCurrentReport() *AdjustableMaxCurrentController_ChargepointMaxCurrentReport_Call {
	return &AdjustableMaxCurrentController_ChargepointMaxCurrentReport_Call{Call: _e.mock.On("ChargepointMaxCurrentReport")}
}

func (_c *AdjustableMaxCurrentController_ChargepointMaxCurrentReport_Call) Run(run func()) *AdjustableMaxCurrentController_ChargepointMaxCurrentReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AdjustableMaxCurrentController_ChargepointMaxCurrentReport_Call) Return(_a0 int, _a1 error) *AdjustableMaxCurrentController_ChargepointMaxCurrentReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdjustableMaxCurrentController_ChargepointMaxCurrentReport_Call) RunAndReturn(run func() (int, error)) *AdjustableMaxCurrentController_ChargepointMaxCurrentReport_Call {
	_c.Call.Return(run)
	return _c
}

// SetChargepointMaxCurrent provides a mock function with given fields: _a0
func (_m *AdjustableMaxCurrentController) SetChargepointMaxCurrent(_a0 int) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetChargepointMaxCurrent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AdjustableMaxCurrentController_SetChargepointMaxCurrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetChargepointMaxCurrent'
type AdjustableMaxCurrentController_SetChargepointMaxCurrent_Call struct {
	*mock.Call
}

// SetChargepointMaxCurrent is a helper method to define mock.On call
//   - _a0 int
func (_e *AdjustableMaxCurrentController_Expecter) SetChargepointMaxCurrent(_a0 any) *AdjustableMaxCurrentController_SetChargepointMaxCurrent_Call {
	return &AdjustableMaxCurrentController_SetChargepointMaxCurrent_Call{Call: _e.mock.On("SetChargepointMaxCurrent", _a0)}
}

func (_c *AdjustableMaxCurrentController_SetChargepointMaxCurrent_Call) Run(run func(_a0 int)) *AdjustableMaxCurrentController_SetChargepointMaxCurrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *AdjustableMaxCurrentController_SetChargepointMaxCurrent_Call) Return(_a0 error) *AdjustableMaxCurrentController_SetChargepointMaxCurrent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AdjustableMaxCurrentController_SetChargepointMaxCurrent_Call) RunAndReturn(run func(int) error) *AdjustableMaxCurrentController_SetChargepointMaxCurrent_Call {
	_c.Call.Return(run)
	return _c
}

// NewAdjustableMaxCurrentController creates a new instance of AdjustableMaxCurrentController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdjustableMaxCurrentController(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdjustableMaxCurrentController {
	mock := &AdjustableMaxCurrentController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
