// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedchargepoint

import (
	chargepoint "github.com/futurehomeno/cliffhanger/adapter/service/chargepoint"
	mock "github.com/stretchr/testify/mock"
)

// CableLockAwareController is an autogenerated mock type for the CableLockAwareController type
type CableLockAwareController struct {
	mock.Mock
}

type CableLockAwareController_Expecter struct {
	mock *mock.Mock
}

func (_m *CableLockAwareController) EXPECT() *CableLockAwareController_Expecter {
	return &CableLockAwareController_Expecter{mock: &_m.Mock}
}

// ChargepointCableLockReport provides a mock function with no fields
func (_m *CableLockAwareController) ChargepointCableLockReport() (*chargepoint.CableReport, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChargepointCableLockReport")
	}

	var r0 *chargepoint.CableReport
	var r1 error
	if rf, ok := ret.Get(0).(func() (*chargepoint.CableReport, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *chargepoint.CableReport); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chargepoint.CableReport)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CableLockAwareController_ChargepointCableLockReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChargepointCableLockReport'
type CableLockAwareController_ChargepointCableLockReport_Call struct {
	*mock.Call
}

// ChargepointCableLockReport is a helper method to define mock.On call
func (_e *CableLockAwareController_Expecter) ChargepointCableLockReport() *CableLockAwareController_ChargepointCableLockReport_Call {
	return &CableLockAwareController_ChargepointCableLockReport_Call{Call: _e.mock.On("ChargepointCableLockReport")}
}

func (_c *CableLockAwareController_ChargepointCableLockReport_Call) Run(run func()) *CableLockAwareController_ChargepointCableLockReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CableLockAwareController_ChargepointCableLockReport_Call) Return(_a0 *chargepoint.CableReport, _a1 error) *CableLockAwareController_ChargepointCableLockReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CableLockAwareController_ChargepointCableLockReport_Call) RunAndReturn(run func() (*chargepoint.CableReport, error)) *CableLockAwareController_ChargepointCableLockReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewCableLockAwareController creates a new instance of CableLockAwareController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCableLockAwareController(t interface {
	mock.TestingT
	Cleanup(func())
}) *CableLockAwareController {
	mock := &CableLockAwareController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
