// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedchargepoint

import (
	chargepoint "github.com/futurehomeno/cliffhanger/adapter/service/chargepoint"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// ChargepointCurrentSessionReport provides a mock function with no fields
func (_m *Controller) ChargepointCurrentSessionReport() (*chargepoint.SessionReport, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChargepointCurrentSessionReport")
	}

	var r0 *chargepoint.SessionReport
	var r1 error
	if rf, ok := ret.Get(0).(func() (*chargepoint.SessionReport, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *chargepoint.SessionReport); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chargepoint.SessionReport)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_ChargepointCurrentSessionReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChargepointCurrentSessionReport'
type Controller_ChargepointCurrentSessionReport_Call struct {
	*mock.Call
}

// ChargepointCurrentSessionReport is a helper method to define mock.On call
func (_e *Controller_Expecter) ChargepointCurrentSessionReport() *Controller_ChargepointCurrentSessionReport_Call {
	return &Controller_ChargepointCurrentSessionReport_Call{Call: _e.mock.On("ChargepointCurrentSessionReport")}
}

func (_c *Controller_ChargepointCurrentSessionReport_Call) Run(run func()) *Controller_ChargepointCurrentSessionReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_ChargepointCurrentSessionReport_Call) Return(_a0 *chargepoint.SessionReport, _a1 error) *Controller_ChargepointCurrentSessionReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_ChargepointCurrentSessionReport_Call) RunAndReturn(run func() (*chargepoint.SessionReport, error)) *Controller_ChargepointCurrentSessionReport_Call {
	_c.Call.Return(run)
	return _c
}

// ChargepointStateReport provides a mock function with no fields
func (_m *Controller) ChargepointStateReport() (chargepoint.State, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChargepointStateReport")
	}

	var r0 chargepoint.State
	var r1 error
	if rf, ok := ret.Get(0).(func() (chargepoint.State, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() chargepoint.State); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(chargepoint.State)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Controller_ChargepointStateReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChargepointStateReport'
type Controller_ChargepointStateReport_Call struct {
	*mock.Call
}

// ChargepointStateReport is a helper method to define mock.On call
func (_e *Controller_Expecter) ChargepointStateReport() *Controller_ChargepointStateReport_Call {
	return &Controller_ChargepointStateReport_Call{Call: _e.mock.On("ChargepointStateReport")}
}

func (_c *Controller_ChargepointStateReport_Call) Run(run func()) *Controller_ChargepointStateReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_ChargepointStateReport_Call) Return(_a0 chargepoint.State, _a1 error) *Controller_ChargepointStateReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Controller_ChargepointStateReport_Call) RunAndReturn(run func() (chargepoint.State, error)) *Controller_ChargepointStateReport_Call {
	_c.Call.Return(run)
	return _c
}

// StartChargepointCharging provides a mock function with given fields: settings
func (_m *Controller) StartChargepointCharging(settings *chargepoint.ChargingSettings) error {
	ret := _m.Called(settings)

	if len(ret) == 0 {
		panic("no return value specified for StartChargepointCharging")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*chargepoint.ChargingSettings) error); ok {
		r0 = rf(settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_StartChargepointCharging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartChargepointCharging'
type Controller_StartChargepointCharging_Call struct {
	*mock.Call
}

// StartChargepointCharging is a helper method to define mock.On call
//   - settings *chargepoint.ChargingSettings
func (_e *Controller_Expecter) StartChargepointCharging(settings interface{}) *Controller_StartChargepointCharging_Call {
	return &Controller_StartChargepointCharging_Call{Call: _e.mock.On("StartChargepointCharging", settings)}
}

func (_c *Controller_StartChargepointCharging_Call) Run(run func(settings *chargepoint.ChargingSettings)) *Controller_StartChargepointCharging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*chargepoint.ChargingSettings))
	})
	return _c
}

func (_c *Controller_StartChargepointCharging_Call) Return(_a0 error) *Controller_StartChargepointCharging_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_StartChargepointCharging_Call) RunAndReturn(run func(*chargepoint.ChargingSettings) error) *Controller_StartChargepointCharging_Call {
	_c.Call.Return(run)
	return _c
}

// StopChargepointCharging provides a mock function with no fields
func (_m *Controller) StopChargepointCharging() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StopChargepointCharging")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Controller_StopChargepointCharging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopChargepointCharging'
type Controller_StopChargepointCharging_Call struct {
	*mock.Call
}

// StopChargepointCharging is a helper method to define mock.On call
func (_e *Controller_Expecter) StopChargepointCharging() *Controller_StopChargepointCharging_Call {
	return &Controller_StopChargepointCharging_Call{Call: _e.mock.On("StopChargepointCharging")}
}

func (_c *Controller_StopChargepointCharging_Call) Run(run func()) *Controller_StopChargepointCharging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_StopChargepointCharging_Call) Return(_a0 error) *Controller_StopChargepointCharging_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Controller_StopChargepointCharging_Call) RunAndReturn(run func() error) *Controller_StopChargepointCharging_Call {
	_c.Call.Return(run)
	return _c
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
