name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name'
        required: true
        default: 'beta'
        type: choice
        options:
          - prod
          - beta
      tag:
        description: 'Container image tag'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    timeout-minutes: 60
    runs-on: fh-ubuntu-22.04
    container:
      image: docker:dind
    steps:
      - name: Deploy the service
        uses: futurehomeno/github-actions/deploy@main
        with:
          secrets: ${{ toJSON(secrets) }}
          environment: ${{ inputs.environment }}
          tag: ${{ inputs.tag }}
