// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedadapter

import (
	adapter "github.com/futurehomeno/cliffhanger/adapter"
	fimptype "github.com/futurehomeno/fimpgo/fimptype"
	mock "github.com/stretchr/testify/mock"
)

// Adapter is an autogenerated mock type for the Adapter type
type Adapter struct {
	mock.Mock
}

type Adapter_Expecter struct {
	mock *mock.Mock
}

func (_m *Adapter) EXPECT() *Adapter_Expecter {
	return &Adapter_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *Adapter) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Adapter_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type Adapter_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *Adapter_Expecter) Address() *Adapter_Address_Call {
	return &Adapter_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *Adapter_Address_Call) Run(run func()) *Adapter_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Adapter_Address_Call) Return(_a0 string) *Adapter_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Adapter_Address_Call) RunAndReturn(run func() string) *Adapter_Address_Call {
	_c.Call.Return(run)
	return _c
}

// CreateThing provides a mock function with given fields: seed
func (_m *Adapter) CreateThing(seed *adapter.ThingSeed) error {
	ret := _m.Called(seed)

	if len(ret) == 0 {
		panic("no return value specified for CreateThing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*adapter.ThingSeed) error); ok {
		r0 = rf(seed)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Adapter_CreateThing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateThing'
type Adapter_CreateThing_Call struct {
	*mock.Call
}

// CreateThing is a helper method to define mock.On call
//   - seed *adapter.ThingSeed
func (_e *Adapter_Expecter) CreateThing(seed any) *Adapter_CreateThing_Call {
	return &Adapter_CreateThing_Call{Call: _e.mock.On("CreateThing", seed)}
}

func (_c *Adapter_CreateThing_Call) Run(run func(seed *adapter.ThingSeed)) *Adapter_CreateThing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*adapter.ThingSeed))
	})
	return _c
}

func (_c *Adapter_CreateThing_Call) Return(_a0 error) *Adapter_CreateThing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Adapter_CreateThing_Call) RunAndReturn(run func(*adapter.ThingSeed) error) *Adapter_CreateThing_Call {
	_c.Call.Return(run)
	return _c
}

// DestroyAllThings provides a mock function with no fields
func (_m *Adapter) DestroyAllThings() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DestroyAllThings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Adapter_DestroyAllThings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DestroyAllThings'
type Adapter_DestroyAllThings_Call struct {
	*mock.Call
}

// DestroyAllThings is a helper method to define mock.On call
func (_e *Adapter_Expecter) DestroyAllThings() *Adapter_DestroyAllThings_Call {
	return &Adapter_DestroyAllThings_Call{Call: _e.mock.On("DestroyAllThings")}
}

func (_c *Adapter_DestroyAllThings_Call) Run(run func()) *Adapter_DestroyAllThings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Adapter_DestroyAllThings_Call) Return(_a0 error) *Adapter_DestroyAllThings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Adapter_DestroyAllThings_Call) RunAndReturn(run func() error) *Adapter_DestroyAllThings_Call {
	_c.Call.Return(run)
	return _c
}

// DestroyThingByAddress provides a mock function with given fields: address
func (_m *Adapter) DestroyThingByAddress(address string) error {
	ret := _m.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for DestroyThingByAddress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(address)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Adapter_DestroyThingByAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DestroyThingByAddress'
type Adapter_DestroyThingByAddress_Call struct {
	*mock.Call
}

// DestroyThingByAddress is a helper method to define mock.On call
//   - address string
func (_e *Adapter_Expecter) DestroyThingByAddress(address any) *Adapter_DestroyThingByAddress_Call {
	return &Adapter_DestroyThingByAddress_Call{Call: _e.mock.On("DestroyThingByAddress", address)}
}

func (_c *Adapter_DestroyThingByAddress_Call) Run(run func(address string)) *Adapter_DestroyThingByAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Adapter_DestroyThingByAddress_Call) Return(_a0 error) *Adapter_DestroyThingByAddress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Adapter_DestroyThingByAddress_Call) RunAndReturn(run func(string) error) *Adapter_DestroyThingByAddress_Call {
	_c.Call.Return(run)
	return _c
}

// DestroyThingByID provides a mock function with given fields: id
func (_m *Adapter) DestroyThingByID(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DestroyThingByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Adapter_DestroyThingByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DestroyThingByID'
type Adapter_DestroyThingByID_Call struct {
	*mock.Call
}

// DestroyThingByID is a helper method to define mock.On call
//   - id string
func (_e *Adapter_Expecter) DestroyThingByID(id any) *Adapter_DestroyThingByID_Call {
	return &Adapter_DestroyThingByID_Call{Call: _e.mock.On("DestroyThingByID", id)}
}

func (_c *Adapter_DestroyThingByID_Call) Run(run func(id string)) *Adapter_DestroyThingByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Adapter_DestroyThingByID_Call) Return(_a0 error) *Adapter_DestroyThingByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Adapter_DestroyThingByID_Call) RunAndReturn(run func(string) error) *Adapter_DestroyThingByID_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureThings provides a mock function with given fields: seeds
func (_m *Adapter) EnsureThings(seeds adapter.ThingSeeds) error {
	ret := _m.Called(seeds)

	if len(ret) == 0 {
		panic("no return value specified for EnsureThings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(adapter.ThingSeeds) error); ok {
		r0 = rf(seeds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Adapter_EnsureThings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureThings'
type Adapter_EnsureThings_Call struct {
	*mock.Call
}

// EnsureThings is a helper method to define mock.On call
//   - seeds adapter.ThingSeeds
func (_e *Adapter_Expecter) EnsureThings(seeds any) *Adapter_EnsureThings_Call {
	return &Adapter_EnsureThings_Call{Call: _e.mock.On("EnsureThings", seeds)}
}

func (_c *Adapter_EnsureThings_Call) Run(run func(seeds adapter.ThingSeeds)) *Adapter_EnsureThings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(adapter.ThingSeeds))
	})
	return _c
}

func (_c *Adapter_EnsureThings_Call) Return(_a0 error) *Adapter_EnsureThings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Adapter_EnsureThings_Call) RunAndReturn(run func(adapter.ThingSeeds) error) *Adapter_EnsureThings_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeAddress provides a mock function with given fields: address
func (_m *Adapter) ExchangeAddress(address string) (string, bool) {
	ret := _m.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeAddress")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return rf(address)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(address)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(address)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Adapter_ExchangeAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeAddress'
type Adapter_ExchangeAddress_Call struct {
	*mock.Call
}

// ExchangeAddress is a helper method to define mock.On call
//   - address string
func (_e *Adapter_Expecter) ExchangeAddress(address any) *Adapter_ExchangeAddress_Call {
	return &Adapter_ExchangeAddress_Call{Call: _e.mock.On("ExchangeAddress", address)}
}

func (_c *Adapter_ExchangeAddress_Call) Run(run func(address string)) *Adapter_ExchangeAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Adapter_ExchangeAddress_Call) Return(id string, ok bool) *Adapter_ExchangeAddress_Call {
	_c.Call.Return(id, ok)
	return _c
}

func (_c *Adapter_ExchangeAddress_Call) RunAndReturn(run func(string) (string, bool)) *Adapter_ExchangeAddress_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeID provides a mock function with given fields: id
func (_m *Adapter) ExchangeID(id string) (string, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeID")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Adapter_ExchangeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeID'
type Adapter_ExchangeID_Call struct {
	*mock.Call
}

// ExchangeID is a helper method to define mock.On call
//   - id string
func (_e *Adapter_Expecter) ExchangeID(id any) *Adapter_ExchangeID_Call {
	return &Adapter_ExchangeID_Call{Call: _e.mock.On("ExchangeID", id)}
}

func (_c *Adapter_ExchangeID_Call) Run(run func(id string)) *Adapter_ExchangeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Adapter_ExchangeID_Call) Return(address string, ok bool) *Adapter_ExchangeID_Call {
	_c.Call.Return(address, ok)
	return _c
}

func (_c *Adapter_ExchangeID_Call) RunAndReturn(run func(string) (string, bool)) *Adapter_ExchangeID_Call {
	_c.Call.Return(run)
	return _c
}

// InitializeThings provides a mock function with no fields
func (_m *Adapter) InitializeThings() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitializeThings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Adapter_InitializeThings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeThings'
type Adapter_InitializeThings_Call struct {
	*mock.Call
}

// InitializeThings is a helper method to define mock.On call
func (_e *Adapter_Expecter) InitializeThings() *Adapter_InitializeThings_Call {
	return &Adapter_InitializeThings_Call{Call: _e.mock.On("InitializeThings")}
}

func (_c *Adapter_InitializeThings_Call) Run(run func()) *Adapter_InitializeThings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Adapter_InitializeThings_Call) Return(_a0 error) *Adapter_InitializeThings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Adapter_InitializeThings_Call) RunAndReturn(run func() error) *Adapter_InitializeThings_Call {
	_c.Call.Return(run)
	return _c
}

// IsInitialized provides a mock function with no fields
func (_m *Adapter) IsInitialized() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsInitialized")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Adapter_IsInitialized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsInitialized'
type Adapter_IsInitialized_Call struct {
	*mock.Call
}

// IsInitialized is a helper method to define mock.On call
func (_e *Adapter_Expecter) IsInitialized() *Adapter_IsInitialized_Call {
	return &Adapter_IsInitialized_Call{Call: _e.mock.On("IsInitialized")}
}

func (_c *Adapter_IsInitialized_Call) Run(run func()) *Adapter_IsInitialized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Adapter_IsInitialized_Call) Return(_a0 bool) *Adapter_IsInitialized_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Adapter_IsInitialized_Call) RunAndReturn(run func() bool) *Adapter_IsInitialized_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *Adapter) Name() fimptype.ResourceNameT {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 fimptype.ResourceNameT
	if rf, ok := ret.Get(0).(func() fimptype.ResourceNameT); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(fimptype.ResourceNameT)
	}

	return r0
}

// Adapter_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Adapter_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Adapter_Expecter) Name() *Adapter_Name_Call {
	return &Adapter_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Adapter_Name_Call) Run(run func()) *Adapter_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Adapter_Name_Call) Return(_a0 fimptype.ResourceNameT) *Adapter_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Adapter_Name_Call) RunAndReturn(run func() fimptype.ResourceNameT) *Adapter_Name_Call {
	_c.Call.Return(run)
	return _c
}

// SendConnectivityReport provides a mock function with no fields
func (_m *Adapter) SendConnectivityReport() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendConnectivityReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Adapter_SendConnectivityReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendConnectivityReport'
type Adapter_SendConnectivityReport_Call struct {
	*mock.Call
}

// SendConnectivityReport is a helper method to define mock.On call
func (_e *Adapter_Expecter) SendConnectivityReport() *Adapter_SendConnectivityReport_Call {
	return &Adapter_SendConnectivityReport_Call{Call: _e.mock.On("SendConnectivityReport")}
}

func (_c *Adapter_SendConnectivityReport_Call) Run(run func()) *Adapter_SendConnectivityReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Adapter_SendConnectivityReport_Call) Return(_a0 error) *Adapter_SendConnectivityReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Adapter_SendConnectivityReport_Call) RunAndReturn(run func() error) *Adapter_SendConnectivityReport_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceByTopic provides a mock function with given fields: topic
func (_m *Adapter) ServiceByTopic(topic string) adapter.Service {
	ret := _m.Called(topic)

	if len(ret) == 0 {
		panic("no return value specified for ServiceByTopic")
	}

	var r0 adapter.Service
	if rf, ok := ret.Get(0).(func(string) adapter.Service); ok {
		r0 = rf(topic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adapter.Service)
		}
	}

	return r0
}

// Adapter_ServiceByTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceByTopic'
type Adapter_ServiceByTopic_Call struct {
	*mock.Call
}

// ServiceByTopic is a helper method to define mock.On call
//   - topic string
func (_e *Adapter_Expecter) ServiceByTopic(topic any) *Adapter_ServiceByTopic_Call {
	return &Adapter_ServiceByTopic_Call{Call: _e.mock.On("ServiceByTopic", topic)}
}

func (_c *Adapter_ServiceByTopic_Call) Run(run func(topic string)) *Adapter_ServiceByTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Adapter_ServiceByTopic_Call) Return(_a0 adapter.Service) *Adapter_ServiceByTopic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Adapter_ServiceByTopic_Call) RunAndReturn(run func(string) adapter.Service) *Adapter_ServiceByTopic_Call {
	_c.Call.Return(run)
	return _c
}

// Services provides a mock function with given fields: name
func (_m *Adapter) Services(name fimptype.ServiceNameT) []adapter.Service {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Services")
	}

	var r0 []adapter.Service
	if rf, ok := ret.Get(0).(func(fimptype.ServiceNameT) []adapter.Service); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]adapter.Service)
		}
	}

	return r0
}

// Adapter_Services_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Services'
type Adapter_Services_Call struct {
	*mock.Call
}

// Services is a helper method to define mock.On call
//   - name fimptype.ServiceNameT
func (_e *Adapter_Expecter) Services(name any) *Adapter_Services_Call {
	return &Adapter_Services_Call{Call: _e.mock.On("Services", name)}
}

func (_c *Adapter_Services_Call) Run(run func(name fimptype.ServiceNameT)) *Adapter_Services_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(fimptype.ServiceNameT))
	})
	return _c
}

func (_c *Adapter_Services_Call) Return(_a0 []adapter.Service) *Adapter_Services_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Adapter_Services_Call) RunAndReturn(run func(fimptype.ServiceNameT) []adapter.Service) *Adapter_Services_Call {
	_c.Call.Return(run)
	return _c
}

// ThingByAddress provides a mock function with given fields: address
func (_m *Adapter) ThingByAddress(address string) adapter.Thing {
	ret := _m.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for ThingByAddress")
	}

	var r0 adapter.Thing
	if rf, ok := ret.Get(0).(func(string) adapter.Thing); ok {
		r0 = rf(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adapter.Thing)
		}
	}

	return r0
}

// Adapter_ThingByAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThingByAddress'
type Adapter_ThingByAddress_Call struct {
	*mock.Call
}

// ThingByAddress is a helper method to define mock.On call
//   - address string
func (_e *Adapter_Expecter) ThingByAddress(address any) *Adapter_ThingByAddress_Call {
	return &Adapter_ThingByAddress_Call{Call: _e.mock.On("ThingByAddress", address)}
}

func (_c *Adapter_ThingByAddress_Call) Run(run func(address string)) *Adapter_ThingByAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Adapter_ThingByAddress_Call) Return(_a0 adapter.Thing) *Adapter_ThingByAddress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Adapter_ThingByAddress_Call) RunAndReturn(run func(string) adapter.Thing) *Adapter_ThingByAddress_Call {
	_c.Call.Return(run)
	return _c
}

// ThingByID provides a mock function with given fields: id
func (_m *Adapter) ThingByID(id string) adapter.Thing {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for ThingByID")
	}

	var r0 adapter.Thing
	if rf, ok := ret.Get(0).(func(string) adapter.Thing); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adapter.Thing)
		}
	}

	return r0
}

// Adapter_ThingByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThingByID'
type Adapter_ThingByID_Call struct {
	*mock.Call
}

// ThingByID is a helper method to define mock.On call
//   - id string
func (_e *Adapter_Expecter) ThingByID(id any) *Adapter_ThingByID_Call {
	return &Adapter_ThingByID_Call{Call: _e.mock.On("ThingByID", id)}
}

func (_c *Adapter_ThingByID_Call) Run(run func(id string)) *Adapter_ThingByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Adapter_ThingByID_Call) Return(_a0 adapter.Thing) *Adapter_ThingByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Adapter_ThingByID_Call) RunAndReturn(run func(string) adapter.Thing) *Adapter_ThingByID_Call {
	_c.Call.Return(run)
	return _c
}

// ThingByTopic provides a mock function with given fields: topic
func (_m *Adapter) ThingByTopic(topic string) adapter.Thing {
	ret := _m.Called(topic)

	if len(ret) == 0 {
		panic("no return value specified for ThingByTopic")
	}

	var r0 adapter.Thing
	if rf, ok := ret.Get(0).(func(string) adapter.Thing); ok {
		r0 = rf(topic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adapter.Thing)
		}
	}

	return r0
}

// Adapter_ThingByTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThingByTopic'
type Adapter_ThingByTopic_Call struct {
	*mock.Call
}

// ThingByTopic is a helper method to define mock.On call
//   - topic string
func (_e *Adapter_Expecter) ThingByTopic(topic any) *Adapter_ThingByTopic_Call {
	return &Adapter_ThingByTopic_Call{Call: _e.mock.On("ThingByTopic", topic)}
}

func (_c *Adapter_ThingByTopic_Call) Run(run func(topic string)) *Adapter_ThingByTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Adapter_ThingByTopic_Call) Return(_a0 adapter.Thing) *Adapter_ThingByTopic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Adapter_ThingByTopic_Call) RunAndReturn(run func(string) adapter.Thing) *Adapter_ThingByTopic_Call {
	_c.Call.Return(run)
	return _c
}

// Things provides a mock function with no fields
func (_m *Adapter) Things() []adapter.Thing {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Things")
	}

	var r0 []adapter.Thing
	if rf, ok := ret.Get(0).(func() []adapter.Thing); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]adapter.Thing)
		}
	}

	return r0
}

// Adapter_Things_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Things'
type Adapter_Things_Call struct {
	*mock.Call
}

// Things is a helper method to define mock.On call
func (_e *Adapter_Expecter) Things() *Adapter_Things_Call {
	return &Adapter_Things_Call{Call: _e.mock.On("Things")}
}

func (_c *Adapter_Things_Call) Run(run func()) *Adapter_Things_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Adapter_Things_Call) Return(_a0 []adapter.Thing) *Adapter_Things_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Adapter_Things_Call) RunAndReturn(run func() []adapter.Thing) *Adapter_Things_Call {
	_c.Call.Return(run)
	return _c
}

// NewAdapter creates a new instance of Adapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Adapter {
	mock := &Adapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
