// Code generated by mockery v2.23.0. DO NOT EDIT.

package mockedadapter

import (
	adapter "github.com/futurehomeno/cliffhanger/adapter"
	fimpgo "github.com/futurehomeno/fimpgo"

	mock "github.com/stretchr/testify/mock"
)

// baseAdapter is an autogenerated mock type for the baseAdapter type
type baseAdapter struct {
	mock.Mock
}

// AddThing provides a mock function with given fields: thing
func (_m *baseAdapter) AddThing(thing adapter.Thing) error {
	ret := _m.Called(thing)

	var r0 error
	if rf, ok := ret.Get(0).(func(adapter.Thing) error); ok {
		r0 = rf(thing)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Address provides a mock function with given fields:
func (_m *baseAdapter) Address() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Name provides a mock function with given fields:
func (_m *baseAdapter) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RegisterThing provides a mock function with given fields: thing
func (_m *baseAdapter) RegisterThing(thing adapter.Thing) {
	_m.Called(thing)
}

// RemoveAllThings provides a mock function with given fields:
func (_m *baseAdapter) RemoveAllThings() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveThing provides a mock function with given fields: address
func (_m *baseAdapter) RemoveThing(address string) error {
	ret := _m.Called(address)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(address)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendAllNodesReport provides a mock function with given fields:
func (_m *baseAdapter) SendAllNodesReport() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendExclusionReport provides a mock function with given fields: address
func (_m *baseAdapter) SendExclusionReport(address string) error {
	ret := _m.Called(address)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(address)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceByTopic provides a mock function with given fields: topic
func (_m *baseAdapter) ServiceByTopic(topic string) adapter.Service {
	ret := _m.Called(topic)

	var r0 adapter.Service
	if rf, ok := ret.Get(0).(func(string) adapter.Service); ok {
		r0 = rf(topic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adapter.Service)
		}
	}

	return r0
}

// Services provides a mock function with given fields: name
func (_m *baseAdapter) Services(name string) []adapter.Service {
	ret := _m.Called(name)

	var r0 []adapter.Service
	if rf, ok := ret.Get(0).(func(string) []adapter.Service); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]adapter.Service)
		}
	}

	return r0
}

// ThingByAddress provides a mock function with given fields: address
func (_m *baseAdapter) ThingByAddress(address string) adapter.Thing {
	ret := _m.Called(address)

	var r0 adapter.Thing
	if rf, ok := ret.Get(0).(func(string) adapter.Thing); ok {
		r0 = rf(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adapter.Thing)
		}
	}

	return r0
}

// ThingByTopic provides a mock function with given fields: topic
func (_m *baseAdapter) ThingByTopic(topic string) adapter.Thing {
	ret := _m.Called(topic)

	var r0 adapter.Thing
	if rf, ok := ret.Get(0).(func(string) adapter.Thing); ok {
		r0 = rf(topic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adapter.Thing)
		}
	}

	return r0
}

// Things provides a mock function with given fields:
func (_m *baseAdapter) Things() []adapter.Thing {
	ret := _m.Called()

	var r0 []adapter.Thing
	if rf, ok := ret.Get(0).(func() []adapter.Thing); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]adapter.Thing)
		}
	}

	return r0
}

// UnregisterAllThings provides a mock function with given fields:
func (_m *baseAdapter) UnregisterAllThings() {
	_m.Called()
}

// UnregisterThing provides a mock function with given fields: address
func (_m *baseAdapter) UnregisterThing(address string) {
	_m.Called(address)
}

// publishAdapterMessage provides a mock function with given fields: message
func (_m *baseAdapter) publishAdapterMessage(message *fimpgo.FimpMessage) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(*fimpgo.FimpMessage) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// publishServiceMessage provides a mock function with given fields: service, message
func (_m *baseAdapter) publishServiceMessage(service adapter.Service, message *fimpgo.FimpMessage) error {
	ret := _m.Called(service, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(adapter.Service, *fimpgo.FimpMessage) error); ok {
		r0 = rf(service, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// publishThingMessage provides a mock function with given fields: thing, message
func (_m *baseAdapter) publishThingMessage(thing adapter.Thing, message *fimpgo.FimpMessage) error {
	ret := _m.Called(thing, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(adapter.Thing, *fimpgo.FimpMessage) error); ok {
		r0 = rf(thing, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewBaseAdapter interface {
	mock.TestingT
	Cleanup(func())
}

// newBaseAdapter creates a new instance of baseAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newBaseAdapter(t mockConstructorTestingTnewBaseAdapter) *baseAdapter {
	mock := &baseAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
