// Code generated by mockery v2.23.0. DO NOT EDIT.

package mockedadapter

import (
	adapter "github.com/futurehomeno/cliffhanger/adapter"
	mock "github.com/stretchr/testify/mock"
)

// Connector is an autogenerated mock type for the Connector type
type Connector struct {
	mock.Mock
}

// Connect provides a mock function with given fields: t
func (_m *Connector) Connect(t adapter.Thing) {
	_m.Called(t)
}

// Connectivity provides a mock function with given fields:
func (_m *Connector) Connectivity() *adapter.ConnectivityDetails {
	ret := _m.Called()

	var r0 *adapter.ConnectivityDetails
	if rf, ok := ret.Get(0).(func() *adapter.ConnectivityDetails); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adapter.ConnectivityDetails)
		}
	}

	return r0
}

// Disconnect provides a mock function with given fields: t
func (_m *Connector) Disconnect(t adapter.Thing) {
	_m.Called(t)
}

// Ping provides a mock function with given fields:
func (_m *Connector) Ping() *adapter.PingDetails {
	ret := _m.Called()

	var r0 *adapter.PingDetails
	if rf, ok := ret.Get(0).(func() *adapter.PingDetails); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adapter.PingDetails)
		}
	}

	return r0
}

type mockConstructorTestingTNewConnector interface {
	mock.TestingT
	Cleanup(func())
}

// NewConnector creates a new instance of Connector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConnector(t mockConstructorTestingTNewConnector) *Connector {
	mock := &Connector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
