// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedadapter

import (
	adapter "github.com/futurehomeno/cliffhanger/adapter"
	mock "github.com/stretchr/testify/mock"
)

// Connector is an autogenerated mock type for the Connector type
type Connector struct {
	mock.Mock
}

type Connector_Expecter struct {
	mock *mock.Mock
}

func (_m *Connector) EXPECT() *Connector_Expecter {
	return &Connector_Expecter{mock: &_m.Mock}
}

// Connectivity provides a mock function with no fields
func (_m *Connector) Connectivity() *adapter.ConnectivityDetails {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connectivity")
	}

	var r0 *adapter.ConnectivityDetails
	if rf, ok := ret.Get(0).(func() *adapter.ConnectivityDetails); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adapter.ConnectivityDetails)
		}
	}

	return r0
}

// Connector_Connectivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connectivity'
type Connector_Connectivity_Call struct {
	*mock.Call
}

// Connectivity is a helper method to define mock.On call
func (_e *Connector_Expecter) Connectivity() *Connector_Connectivity_Call {
	return &Connector_Connectivity_Call{Call: _e.mock.On("Connectivity")}
}

func (_c *Connector_Connectivity_Call) Run(run func()) *Connector_Connectivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connector_Connectivity_Call) Return(_a0 *adapter.ConnectivityDetails) *Connector_Connectivity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Connector_Connectivity_Call) RunAndReturn(run func() *adapter.ConnectivityDetails) *Connector_Connectivity_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with no fields
func (_m *Connector) Ping() *adapter.PingDetails {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 *adapter.PingDetails
	if rf, ok := ret.Get(0).(func() *adapter.PingDetails); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adapter.PingDetails)
		}
	}

	return r0
}

// Connector_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type Connector_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *Connector_Expecter) Ping() *Connector_Ping_Call {
	return &Connector_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *Connector_Ping_Call) Run(run func()) *Connector_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connector_Ping_Call) Return(_a0 *adapter.PingDetails) *Connector_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Connector_Ping_Call) RunAndReturn(run func() *adapter.PingDetails) *Connector_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewConnector creates a new instance of Connector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *Connector {
	mock := &Connector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
