// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedadapter

import (
	adapter "github.com/futurehomeno/cliffhanger/adapter"
	fimptype "github.com/futurehomeno/fimpgo/fimptype"
	mock "github.com/stretchr/testify/mock"
)

// ServiceRegistry is an autogenerated mock type for the ServiceRegistry type
type ServiceRegistry struct {
	mock.Mock
}

type ServiceRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceRegistry) EXPECT() *ServiceRegistry_Expecter {
	return &ServiceRegistry_Expecter{mock: &_m.Mock}
}

// IsInitialized provides a mock function with no fields
func (_m *ServiceRegistry) IsInitialized() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsInitialized")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ServiceRegistry_IsInitialized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsInitialized'
type ServiceRegistry_IsInitialized_Call struct {
	*mock.Call
}

// IsInitialized is a helper method to define mock.On call
func (_e *ServiceRegistry_Expecter) IsInitialized() *ServiceRegistry_IsInitialized_Call {
	return &ServiceRegistry_IsInitialized_Call{Call: _e.mock.On("IsInitialized")}
}

func (_c *ServiceRegistry_IsInitialized_Call) Run(run func()) *ServiceRegistry_IsInitialized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceRegistry_IsInitialized_Call) Return(_a0 bool) *ServiceRegistry_IsInitialized_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceRegistry_IsInitialized_Call) RunAndReturn(run func() bool) *ServiceRegistry_IsInitialized_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceByTopic provides a mock function with given fields: topic
func (_m *ServiceRegistry) ServiceByTopic(topic string) adapter.Service {
	ret := _m.Called(topic)

	if len(ret) == 0 {
		panic("no return value specified for ServiceByTopic")
	}

	var r0 adapter.Service
	if rf, ok := ret.Get(0).(func(string) adapter.Service); ok {
		r0 = rf(topic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adapter.Service)
		}
	}

	return r0
}

// ServiceRegistry_ServiceByTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceByTopic'
type ServiceRegistry_ServiceByTopic_Call struct {
	*mock.Call
}

// ServiceByTopic is a helper method to define mock.On call
//   - topic string
func (_e *ServiceRegistry_Expecter) ServiceByTopic(topic any) *ServiceRegistry_ServiceByTopic_Call {
	return &ServiceRegistry_ServiceByTopic_Call{Call: _e.mock.On("ServiceByTopic", topic)}
}

func (_c *ServiceRegistry_ServiceByTopic_Call) Run(run func(topic string)) *ServiceRegistry_ServiceByTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ServiceRegistry_ServiceByTopic_Call) Return(_a0 adapter.Service) *ServiceRegistry_ServiceByTopic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceRegistry_ServiceByTopic_Call) RunAndReturn(run func(string) adapter.Service) *ServiceRegistry_ServiceByTopic_Call {
	_c.Call.Return(run)
	return _c
}

// Services provides a mock function with given fields: name
func (_m *ServiceRegistry) Services(name fimptype.ServiceNameT) []adapter.Service {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Services")
	}

	var r0 []adapter.Service
	if rf, ok := ret.Get(0).(func(fimptype.ServiceNameT) []adapter.Service); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]adapter.Service)
		}
	}

	return r0
}

// ServiceRegistry_Services_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Services'
type ServiceRegistry_Services_Call struct {
	*mock.Call
}

// Services is a helper method to define mock.On call
//   - name fimptype.ServiceNameT
func (_e *ServiceRegistry_Expecter) Services(name any) *ServiceRegistry_Services_Call {
	return &ServiceRegistry_Services_Call{Call: _e.mock.On("Services", name)}
}

func (_c *ServiceRegistry_Services_Call) Run(run func(name fimptype.ServiceNameT)) *ServiceRegistry_Services_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(fimptype.ServiceNameT))
	})
	return _c
}

func (_c *ServiceRegistry_Services_Call) Return(_a0 []adapter.Service) *ServiceRegistry_Services_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceRegistry_Services_Call) RunAndReturn(run func(fimptype.ServiceNameT) []adapter.Service) *ServiceRegistry_Services_Call {
	_c.Call.Return(run)
	return _c
}

// NewServiceRegistry creates a new instance of ServiceRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceRegistry {
	mock := &ServiceRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
