// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedadapter

import (
	adapter "github.com/futurehomeno/cliffhanger/adapter"
	fimpgo "github.com/futurehomeno/fimpgo"

	mock "github.com/stretchr/testify/mock"
)

// ServicePublisher is an autogenerated mock type for the ServicePublisher type
type ServicePublisher struct {
	mock.Mock
}

type ServicePublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *ServicePublisher) EXPECT() *ServicePublisher_Expecter {
	return &ServicePublisher_Expecter{mock: &_m.Mock}
}

// PublishServiceEvent provides a mock function with given fields: service, payload
func (_m *ServicePublisher) PublishServiceEvent(service adapter.Service, payload adapter.ServiceEvent) {
	_m.Called(service, payload)
}

// ServicePublisher_PublishServiceEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishServiceEvent'
type ServicePublisher_PublishServiceEvent_Call struct {
	*mock.Call
}

// PublishServiceEvent is a helper method to define mock.On call
//   - service adapter.Service
//   - payload adapter.ServiceEvent
func (_e *ServicePublisher_Expecter) PublishServiceEvent(service interface{}, payload interface{}) *ServicePublisher_PublishServiceEvent_Call {
	return &ServicePublisher_PublishServiceEvent_Call{Call: _e.mock.On("PublishServiceEvent", service, payload)}
}

func (_c *ServicePublisher_PublishServiceEvent_Call) Run(run func(service adapter.Service, payload adapter.ServiceEvent)) *ServicePublisher_PublishServiceEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(adapter.Service), args[1].(adapter.ServiceEvent))
	})
	return _c
}

func (_c *ServicePublisher_PublishServiceEvent_Call) Return() *ServicePublisher_PublishServiceEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServicePublisher_PublishServiceEvent_Call) RunAndReturn(run func(adapter.Service, adapter.ServiceEvent)) *ServicePublisher_PublishServiceEvent_Call {
	_c.Run(run)
	return _c
}

// PublishServiceMessage provides a mock function with given fields: service, message
func (_m *ServicePublisher) PublishServiceMessage(service adapter.Service, message *fimpgo.FimpMessage) error {
	ret := _m.Called(service, message)

	if len(ret) == 0 {
		panic("no return value specified for PublishServiceMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(adapter.Service, *fimpgo.FimpMessage) error); ok {
		r0 = rf(service, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServicePublisher_PublishServiceMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishServiceMessage'
type ServicePublisher_PublishServiceMessage_Call struct {
	*mock.Call
}

// PublishServiceMessage is a helper method to define mock.On call
//   - service adapter.Service
//   - message *fimpgo.FimpMessage
func (_e *ServicePublisher_Expecter) PublishServiceMessage(service interface{}, message interface{}) *ServicePublisher_PublishServiceMessage_Call {
	return &ServicePublisher_PublishServiceMessage_Call{Call: _e.mock.On("PublishServiceMessage", service, message)}
}

func (_c *ServicePublisher_PublishServiceMessage_Call) Run(run func(service adapter.Service, message *fimpgo.FimpMessage)) *ServicePublisher_PublishServiceMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(adapter.Service), args[1].(*fimpgo.FimpMessage))
	})
	return _c
}

func (_c *ServicePublisher_PublishServiceMessage_Call) Return(_a0 error) *ServicePublisher_PublishServiceMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServicePublisher_PublishServiceMessage_Call) RunAndReturn(run func(adapter.Service, *fimpgo.FimpMessage) error) *ServicePublisher_PublishServiceMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewServicePublisher creates a new instance of ServicePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServicePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServicePublisher {
	mock := &ServicePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
