// Code generated by mockery v2.23.0. DO NOT EDIT.

package mockedadapter

import (
	adapter "github.com/futurehomeno/cliffhanger/adapter"
	mock "github.com/stretchr/testify/mock"
)

// ThingFactory is an autogenerated mock type for the ThingFactory type
type ThingFactory struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, thingState
func (_m *ThingFactory) Create(_a0 adapter.Adapter, thingState adapter.ThingState) (adapter.Thing, error) {
	ret := _m.Called(_a0, thingState)

	var r0 adapter.Thing
	var r1 error
	if rf, ok := ret.Get(0).(func(adapter.Adapter, adapter.ThingState) (adapter.Thing, error)); ok {
		return rf(_a0, thingState)
	}
	if rf, ok := ret.Get(0).(func(adapter.Adapter, adapter.ThingState) adapter.Thing); ok {
		r0 = rf(_a0, thingState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adapter.Thing)
		}
	}

	if rf, ok := ret.Get(1).(func(adapter.Adapter, adapter.ThingState) error); ok {
		r1 = rf(_a0, thingState)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewThingFactory interface {
	mock.TestingT
	Cleanup(func())
}

// NewThingFactory creates a new instance of ThingFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewThingFactory(t mockConstructorTestingTNewThingFactory) *ThingFactory {
	mock := &ThingFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
