// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedadapter

import mock "github.com/stretchr/testify/mock"

// ThingState is an autogenerated mock type for the ThingState type
type ThingState struct {
	mock.Mock
}

type ThingState_Expecter struct {
	mock *mock.Mock
}

func (_m *ThingState) EXPECT() *ThingState_Expecter {
	return &ThingState_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *ThingState) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ThingState_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type ThingState_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *ThingState_Expecter) Address() *ThingState_Address_Call {
	return &ThingState_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *ThingState_Address_Call) Run(run func()) *ThingState_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ThingState_Address_Call) Return(_a0 string) *ThingState_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ThingState_Address_Call) RunAndReturn(run func() string) *ThingState_Address_Call {
	_c.Call.Return(run)
	return _c
}

// GetInclusionChecksum provides a mock function with no fields
func (_m *ThingState) GetInclusionChecksum() uint32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInclusionChecksum")
	}

	var r0 uint32
	if rf, ok := ret.Get(0).(func() uint32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint32)
	}

	return r0
}

// ThingState_GetInclusionChecksum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInclusionChecksum'
type ThingState_GetInclusionChecksum_Call struct {
	*mock.Call
}

// GetInclusionChecksum is a helper method to define mock.On call
func (_e *ThingState_Expecter) GetInclusionChecksum() *ThingState_GetInclusionChecksum_Call {
	return &ThingState_GetInclusionChecksum_Call{Call: _e.mock.On("GetInclusionChecksum")}
}

func (_c *ThingState_GetInclusionChecksum_Call) Run(run func()) *ThingState_GetInclusionChecksum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ThingState_GetInclusionChecksum_Call) Return(_a0 uint32) *ThingState_GetInclusionChecksum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ThingState_GetInclusionChecksum_Call) RunAndReturn(run func() uint32) *ThingState_GetInclusionChecksum_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *ThingState) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ThingState_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type ThingState_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *ThingState_Expecter) ID() *ThingState_ID_Call {
	return &ThingState_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *ThingState_ID_Call) Run(run func()) *ThingState_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ThingState_ID_Call) Return(_a0 string) *ThingState_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ThingState_ID_Call) RunAndReturn(run func() string) *ThingState_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function with given fields: model
func (_m *ThingState) Info(model any) error {
	ret := _m.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any) error); ok {
		r0 = rf(model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ThingState_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type ThingState_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - model any
func (_e *ThingState_Expecter) Info(model any) *ThingState_Info_Call {
	return &ThingState_Info_Call{Call: _e.mock.On("Info", model)}
}

func (_c *ThingState_Info_Call) Run(run func(model any)) *ThingState_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *ThingState_Info_Call) Return(_a0 error) *ThingState_Info_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ThingState_Info_Call) RunAndReturn(run func(any) error) *ThingState_Info_Call {
	_c.Call.Return(run)
	return _c
}

// SetInclusionChecksum provides a mock function with given fields: checksum
func (_m *ThingState) SetInclusionChecksum(checksum uint32) error {
	ret := _m.Called(checksum)

	if len(ret) == 0 {
		panic("no return value specified for SetInclusionChecksum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint32) error); ok {
		r0 = rf(checksum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ThingState_SetInclusionChecksum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetInclusionChecksum'
type ThingState_SetInclusionChecksum_Call struct {
	*mock.Call
}

// SetInclusionChecksum is a helper method to define mock.On call
//   - checksum uint32
func (_e *ThingState_Expecter) SetInclusionChecksum(checksum any) *ThingState_SetInclusionChecksum_Call {
	return &ThingState_SetInclusionChecksum_Call{Call: _e.mock.On("SetInclusionChecksum", checksum)}
}

func (_c *ThingState_SetInclusionChecksum_Call) Run(run func(checksum uint32)) *ThingState_SetInclusionChecksum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint32))
	})
	return _c
}

func (_c *ThingState_SetInclusionChecksum_Call) Return(_a0 error) *ThingState_SetInclusionChecksum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ThingState_SetInclusionChecksum_Call) RunAndReturn(run func(uint32) error) *ThingState_SetInclusionChecksum_Call {
	_c.Call.Return(run)
	return _c
}

// SetState provides a mock function with given fields: model
func (_m *ThingState) SetState(model any) error {
	ret := _m.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for SetState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any) error); ok {
		r0 = rf(model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ThingState_SetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetState'
type ThingState_SetState_Call struct {
	*mock.Call
}

// SetState is a helper method to define mock.On call
//   - model any
func (_e *ThingState_Expecter) SetState(model any) *ThingState_SetState_Call {
	return &ThingState_SetState_Call{Call: _e.mock.On("SetState", model)}
}

func (_c *ThingState_SetState_Call) Run(run func(model any)) *ThingState_SetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *ThingState_SetState_Call) Return(_a0 error) *ThingState_SetState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ThingState_SetState_Call) RunAndReturn(run func(any) error) *ThingState_SetState_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function with given fields: model
func (_m *ThingState) State(model any) error {
	ret := _m.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any) error); ok {
		r0 = rf(model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ThingState_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type ThingState_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
//   - model any
func (_e *ThingState_Expecter) State(model any) *ThingState_State_Call {
	return &ThingState_State_Call{Call: _e.mock.On("State", model)}
}

func (_c *ThingState_State_Call) Run(run func(model any)) *ThingState_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *ThingState_State_Call) Return(_a0 error) *ThingState_State_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ThingState_State_Call) RunAndReturn(run func(any) error) *ThingState_State_Call {
	_c.Call.Return(run)
	return _c
}

// NewThingState creates a new instance of ThingState. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewThingState(t interface {
	mock.TestingT
	Cleanup(func())
}) *ThingState {
	mock := &ThingState{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
