// Code generated by mockery v2.36.0. DO NOT EDIT.

package mockedadapter

import (
	adapter "github.com/futurehomeno/cliffhanger/adapter"
	mock "github.com/stretchr/testify/mock"
)

// ThingUpdate is an autogenerated mock type for the ThingUpdate type
type ThingUpdate struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *ThingUpdate) Execute(_a0 adapter.Thing) {
	_m.Called(_a0)
}

// NewThingUpdate creates a new instance of ThingUpdate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewThingUpdate(t interface {
	mock.TestingT
	Cleanup(func())
}) *ThingUpdate {
	mock := &ThingUpdate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
