// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedadapter

import (
	adapter "github.com/futurehomeno/cliffhanger/adapter"
	mock "github.com/stretchr/testify/mock"
)

// ThingFactory is an autogenerated mock type for the ThingFactory type
type ThingFactory struct {
	mock.Mock
}

type ThingFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *ThingFactory) EXPECT() *ThingFactory_Expecter {
	return &ThingFactory_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, publisher, thingState
func (_m *ThingFactory) Create(_a0 adapter.Adapter, publisher adapter.Publisher, thingState adapter.ThingState) (adapter.Thing, error) {
	ret := _m.Called(_a0, publisher, thingState)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 adapter.Thing
	var r1 error
	if rf, ok := ret.Get(0).(func(adapter.Adapter, adapter.Publisher, adapter.ThingState) (adapter.Thing, error)); ok {
		return rf(_a0, publisher, thingState)
	}
	if rf, ok := ret.Get(0).(func(adapter.Adapter, adapter.Publisher, adapter.ThingState) adapter.Thing); ok {
		r0 = rf(_a0, publisher, thingState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adapter.Thing)
		}
	}

	if rf, ok := ret.Get(1).(func(adapter.Adapter, adapter.Publisher, adapter.ThingState) error); ok {
		r1 = rf(_a0, publisher, thingState)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ThingFactory_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ThingFactory_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 adapter.Adapter
//   - publisher adapter.Publisher
//   - thingState adapter.ThingState
func (_e *ThingFactory_Expecter) Create(_a0 interface{}, publisher interface{}, thingState interface{}) *ThingFactory_Create_Call {
	return &ThingFactory_Create_Call{Call: _e.mock.On("Create", _a0, publisher, thingState)}
}

func (_c *ThingFactory_Create_Call) Run(run func(_a0 adapter.Adapter, publisher adapter.Publisher, thingState adapter.ThingState)) *ThingFactory_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(adapter.Adapter), args[1].(adapter.Publisher), args[2].(adapter.ThingState))
	})
	return _c
}

func (_c *ThingFactory_Create_Call) Return(_a0 adapter.Thing, _a1 error) *ThingFactory_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ThingFactory_Create_Call) RunAndReturn(run func(adapter.Adapter, adapter.Publisher, adapter.ThingState) (adapter.Thing, error)) *ThingFactory_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewThingFactory creates a new instance of ThingFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewThingFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *ThingFactory {
	mock := &ThingFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
