// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedadapter

import (
	adapter "github.com/futurehomeno/cliffhanger/adapter"
	fimpgo "github.com/futurehomeno/fimpgo"
	mock "github.com/stretchr/testify/mock"
)

// ThingPublisher is an autogenerated mock type for the ThingPublisher type
type ThingPublisher struct {
	mock.Mock
}

type ThingPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *ThingPublisher) EXPECT() *ThingPublisher_Expecter {
	return &ThingPublisher_Expecter{mock: &_m.Mock}
}

// PublishServiceEvent provides a mock function with given fields: service, payload
func (_m *ThingPublisher) PublishServiceEvent(service adapter.Service, payload adapter.ServiceEvent) {
	_m.Called(service, payload)
}

// ThingPublisher_PublishServiceEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishServiceEvent'
type ThingPublisher_PublishServiceEvent_Call struct {
	*mock.Call
}

// PublishServiceEvent is a helper method to define mock.On call
//   - service adapter.Service
//   - payload adapter.ServiceEvent
func (_e *ThingPublisher_Expecter) PublishServiceEvent(service any, payload any) *ThingPublisher_PublishServiceEvent_Call {
	return &ThingPublisher_PublishServiceEvent_Call{Call: _e.mock.On("PublishServiceEvent", service, payload)}
}

func (_c *ThingPublisher_PublishServiceEvent_Call) Run(run func(service adapter.Service, payload adapter.ServiceEvent)) *ThingPublisher_PublishServiceEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(adapter.Service), args[1].(adapter.ServiceEvent))
	})
	return _c
}

func (_c *ThingPublisher_PublishServiceEvent_Call) Return() *ThingPublisher_PublishServiceEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *ThingPublisher_PublishServiceEvent_Call) RunAndReturn(run func(adapter.Service, adapter.ServiceEvent)) *ThingPublisher_PublishServiceEvent_Call {
	_c.Run(run)
	return _c
}

// PublishServiceMessage provides a mock function with given fields: service, message
func (_m *ThingPublisher) PublishServiceMessage(service adapter.Service, message *fimpgo.FimpMessage) error {
	ret := _m.Called(service, message)

	if len(ret) == 0 {
		panic("no return value specified for PublishServiceMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(adapter.Service, *fimpgo.FimpMessage) error); ok {
		r0 = rf(service, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ThingPublisher_PublishServiceMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishServiceMessage'
type ThingPublisher_PublishServiceMessage_Call struct {
	*mock.Call
}

// PublishServiceMessage is a helper method to define mock.On call
//   - service adapter.Service
//   - message *fimpgo.FimpMessage
func (_e *ThingPublisher_Expecter) PublishServiceMessage(service any, message any) *ThingPublisher_PublishServiceMessage_Call {
	return &ThingPublisher_PublishServiceMessage_Call{Call: _e.mock.On("PublishServiceMessage", service, message)}
}

func (_c *ThingPublisher_PublishServiceMessage_Call) Run(run func(service adapter.Service, message *fimpgo.FimpMessage)) *ThingPublisher_PublishServiceMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(adapter.Service), args[1].(*fimpgo.FimpMessage))
	})
	return _c
}

func (_c *ThingPublisher_PublishServiceMessage_Call) Return(_a0 error) *ThingPublisher_PublishServiceMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ThingPublisher_PublishServiceMessage_Call) RunAndReturn(run func(adapter.Service, *fimpgo.FimpMessage) error) *ThingPublisher_PublishServiceMessage_Call {
	_c.Call.Return(run)
	return _c
}

// PublishThingEvent provides a mock function with given fields: thingEvent
func (_m *ThingPublisher) PublishThingEvent(thingEvent adapter.ThingEvent) {
	_m.Called(thingEvent)
}

// ThingPublisher_PublishThingEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishThingEvent'
type ThingPublisher_PublishThingEvent_Call struct {
	*mock.Call
}

// PublishThingEvent is a helper method to define mock.On call
//   - thingEvent adapter.ThingEvent
func (_e *ThingPublisher_Expecter) PublishThingEvent(thingEvent any) *ThingPublisher_PublishThingEvent_Call {
	return &ThingPublisher_PublishThingEvent_Call{Call: _e.mock.On("PublishThingEvent", thingEvent)}
}

func (_c *ThingPublisher_PublishThingEvent_Call) Run(run func(thingEvent adapter.ThingEvent)) *ThingPublisher_PublishThingEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(adapter.ThingEvent))
	})
	return _c
}

func (_c *ThingPublisher_PublishThingEvent_Call) Return() *ThingPublisher_PublishThingEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *ThingPublisher_PublishThingEvent_Call) RunAndReturn(run func(adapter.ThingEvent)) *ThingPublisher_PublishThingEvent_Call {
	_c.Run(run)
	return _c
}

// PublishThingMessage provides a mock function with given fields: thing, message
func (_m *ThingPublisher) PublishThingMessage(thing adapter.Thing, message *fimpgo.FimpMessage) error {
	ret := _m.Called(thing, message)

	if len(ret) == 0 {
		panic("no return value specified for PublishThingMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(adapter.Thing, *fimpgo.FimpMessage) error); ok {
		r0 = rf(thing, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ThingPublisher_PublishThingMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishThingMessage'
type ThingPublisher_PublishThingMessage_Call struct {
	*mock.Call
}

// PublishThingMessage is a helper method to define mock.On call
//   - thing adapter.Thing
//   - message *fimpgo.FimpMessage
func (_e *ThingPublisher_Expecter) PublishThingMessage(thing any, message any) *ThingPublisher_PublishThingMessage_Call {
	return &ThingPublisher_PublishThingMessage_Call{Call: _e.mock.On("PublishThingMessage", thing, message)}
}

func (_c *ThingPublisher_PublishThingMessage_Call) Run(run func(thing adapter.Thing, message *fimpgo.FimpMessage)) *ThingPublisher_PublishThingMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(adapter.Thing), args[1].(*fimpgo.FimpMessage))
	})
	return _c
}

func (_c *ThingPublisher_PublishThingMessage_Call) Return(_a0 error) *ThingPublisher_PublishThingMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ThingPublisher_PublishThingMessage_Call) RunAndReturn(run func(adapter.Thing, *fimpgo.FimpMessage) error) *ThingPublisher_PublishThingMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewThingPublisher creates a new instance of ThingPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewThingPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *ThingPublisher {
	mock := &ThingPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
