// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedadapter

import mock "github.com/stretchr/testify/mock"

// ThingEvent is an autogenerated mock type for the ThingEvent type
type ThingEvent struct {
	mock.Mock
}

type ThingEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *ThingEvent) EXPECT() *ThingEvent_Expecter {
	return &ThingEvent_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *ThingEvent) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ThingEvent_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type ThingEvent_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *ThingEvent_Expecter) Address() *ThingEvent_Address_Call {
	return &ThingEvent_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *ThingEvent_Address_Call) Run(run func()) *ThingEvent_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ThingEvent_Address_Call) Return(_a0 string) *ThingEvent_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ThingEvent_Address_Call) RunAndReturn(run func() string) *ThingEvent_Address_Call {
	_c.Call.Return(run)
	return _c
}

// Class provides a mock function with no fields
func (_m *ThingEvent) Class() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Class")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ThingEvent_Class_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Class'
type ThingEvent_Class_Call struct {
	*mock.Call
}

// Class is a helper method to define mock.On call
func (_e *ThingEvent_Expecter) Class() *ThingEvent_Class_Call {
	return &ThingEvent_Class_Call{Call: _e.mock.On("Class")}
}

func (_c *ThingEvent_Class_Call) Run(run func()) *ThingEvent_Class_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ThingEvent_Class_Call) Return(_a0 string) *ThingEvent_Class_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ThingEvent_Class_Call) RunAndReturn(run func() string) *ThingEvent_Class_Call {
	_c.Call.Return(run)
	return _c
}

// Domain provides a mock function with no fields
func (_m *ThingEvent) Domain() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Domain")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ThingEvent_Domain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Domain'
type ThingEvent_Domain_Call struct {
	*mock.Call
}

// Domain is a helper method to define mock.On call
func (_e *ThingEvent_Expecter) Domain() *ThingEvent_Domain_Call {
	return &ThingEvent_Domain_Call{Call: _e.mock.On("Domain")}
}

func (_c *ThingEvent_Domain_Call) Run(run func()) *ThingEvent_Domain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ThingEvent_Domain_Call) Return(_a0 string) *ThingEvent_Domain_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ThingEvent_Domain_Call) RunAndReturn(run func() string) *ThingEvent_Domain_Call {
	_c.Call.Return(run)
	return _c
}

// NewThingEvent creates a new instance of ThingEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewThingEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *ThingEvent {
	mock := &ThingEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
