// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedadapter

import (
	adapter "github.com/futurehomeno/cliffhanger/adapter"
	mock "github.com/stretchr/testify/mock"
)

// ThingRegistry is an autogenerated mock type for the ThingRegistry type
type ThingRegistry struct {
	mock.Mock
}

type ThingRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *ThingRegistry) EXPECT() *ThingRegistry_Expecter {
	return &ThingRegistry_Expecter{mock: &_m.Mock}
}

// ThingByAddress provides a mock function with given fields: address
func (_m *ThingRegistry) ThingByAddress(address string) adapter.Thing {
	ret := _m.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for ThingByAddress")
	}

	var r0 adapter.Thing
	if rf, ok := ret.Get(0).(func(string) adapter.Thing); ok {
		r0 = rf(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adapter.Thing)
		}
	}

	return r0
}

// ThingRegistry_ThingByAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThingByAddress'
type ThingRegistry_ThingByAddress_Call struct {
	*mock.Call
}

// ThingByAddress is a helper method to define mock.On call
//   - address string
func (_e *ThingRegistry_Expecter) ThingByAddress(address any) *ThingRegistry_ThingByAddress_Call {
	return &ThingRegistry_ThingByAddress_Call{Call: _e.mock.On("ThingByAddress", address)}
}

func (_c *ThingRegistry_ThingByAddress_Call) Run(run func(address string)) *ThingRegistry_ThingByAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ThingRegistry_ThingByAddress_Call) Return(_a0 adapter.Thing) *ThingRegistry_ThingByAddress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ThingRegistry_ThingByAddress_Call) RunAndReturn(run func(string) adapter.Thing) *ThingRegistry_ThingByAddress_Call {
	_c.Call.Return(run)
	return _c
}

// ThingByTopic provides a mock function with given fields: topic
func (_m *ThingRegistry) ThingByTopic(topic string) adapter.Thing {
	ret := _m.Called(topic)

	if len(ret) == 0 {
		panic("no return value specified for ThingByTopic")
	}

	var r0 adapter.Thing
	if rf, ok := ret.Get(0).(func(string) adapter.Thing); ok {
		r0 = rf(topic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adapter.Thing)
		}
	}

	return r0
}

// ThingRegistry_ThingByTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThingByTopic'
type ThingRegistry_ThingByTopic_Call struct {
	*mock.Call
}

// ThingByTopic is a helper method to define mock.On call
//   - topic string
func (_e *ThingRegistry_Expecter) ThingByTopic(topic any) *ThingRegistry_ThingByTopic_Call {
	return &ThingRegistry_ThingByTopic_Call{Call: _e.mock.On("ThingByTopic", topic)}
}

func (_c *ThingRegistry_ThingByTopic_Call) Run(run func(topic string)) *ThingRegistry_ThingByTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ThingRegistry_ThingByTopic_Call) Return(_a0 adapter.Thing) *ThingRegistry_ThingByTopic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ThingRegistry_ThingByTopic_Call) RunAndReturn(run func(string) adapter.Thing) *ThingRegistry_ThingByTopic_Call {
	_c.Call.Return(run)
	return _c
}

// Things provides a mock function with no fields
func (_m *ThingRegistry) Things() []adapter.Thing {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Things")
	}

	var r0 []adapter.Thing
	if rf, ok := ret.Get(0).(func() []adapter.Thing); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]adapter.Thing)
		}
	}

	return r0
}

// ThingRegistry_Things_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Things'
type ThingRegistry_Things_Call struct {
	*mock.Call
}

// Things is a helper method to define mock.On call
func (_e *ThingRegistry_Expecter) Things() *ThingRegistry_Things_Call {
	return &ThingRegistry_Things_Call{Call: _e.mock.On("Things")}
}

func (_c *ThingRegistry_Things_Call) Run(run func()) *ThingRegistry_Things_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ThingRegistry_Things_Call) Return(_a0 []adapter.Thing) *ThingRegistry_Things_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ThingRegistry_Things_Call) RunAndReturn(run func() []adapter.Thing) *ThingRegistry_Things_Call {
	_c.Call.Return(run)
	return _c
}

// NewThingRegistry creates a new instance of ThingRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewThingRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *ThingRegistry {
	mock := &ThingRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
