// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockedadapter

import (
	adapter "github.com/futurehomeno/cliffhanger/adapter"
	fimptype "github.com/futurehomeno/fimpgo/fimptype"
	mock "github.com/stretchr/testify/mock"
)

// Thing is an autogenerated mock type for the Thing type
type Thing struct {
	mock.Mock
}

type Thing_Expecter struct {
	mock *mock.Mock
}

func (_m *Thing) EXPECT() *Thing_Expecter {
	return &Thing_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *Thing) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Thing_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type Thing_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *Thing_Expecter) Address() *Thing_Address_Call {
	return &Thing_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *Thing_Address_Call) Run(run func()) *Thing_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Thing_Address_Call) Return(_a0 string) *Thing_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Thing_Address_Call) RunAndReturn(run func() string) *Thing_Address_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function with no fields
func (_m *Thing) Connect() {
	_m.Called()
}

// Thing_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type Thing_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *Thing_Expecter) Connect() *Thing_Connect_Call {
	return &Thing_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *Thing_Connect_Call) Run(run func()) *Thing_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Thing_Connect_Call) Return() *Thing_Connect_Call {
	_c.Call.Return()
	return _c
}

func (_c *Thing_Connect_Call) RunAndReturn(run func()) *Thing_Connect_Call {
	_c.Run(run)
	return _c
}

// ConnectivityReport provides a mock function with no fields
func (_m *Thing) ConnectivityReport() *adapter.ConnectivityReport {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConnectivityReport")
	}

	var r0 *adapter.ConnectivityReport
	if rf, ok := ret.Get(0).(func() *adapter.ConnectivityReport); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adapter.ConnectivityReport)
		}
	}

	return r0
}

// Thing_ConnectivityReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectivityReport'
type Thing_ConnectivityReport_Call struct {
	*mock.Call
}

// ConnectivityReport is a helper method to define mock.On call
func (_e *Thing_Expecter) ConnectivityReport() *Thing_ConnectivityReport_Call {
	return &Thing_ConnectivityReport_Call{Call: _e.mock.On("ConnectivityReport")}
}

func (_c *Thing_ConnectivityReport_Call) Run(run func()) *Thing_ConnectivityReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Thing_ConnectivityReport_Call) Return(_a0 *adapter.ConnectivityReport) *Thing_ConnectivityReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Thing_ConnectivityReport_Call) RunAndReturn(run func() *adapter.ConnectivityReport) *Thing_ConnectivityReport_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function with no fields
func (_m *Thing) Disconnect() {
	_m.Called()
}

// Thing_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type Thing_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
func (_e *Thing_Expecter) Disconnect() *Thing_Disconnect_Call {
	return &Thing_Disconnect_Call{Call: _e.mock.On("Disconnect")}
}

func (_c *Thing_Disconnect_Call) Run(run func()) *Thing_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Thing_Disconnect_Call) Return() *Thing_Disconnect_Call {
	_c.Call.Return()
	return _c
}

func (_c *Thing_Disconnect_Call) RunAndReturn(run func()) *Thing_Disconnect_Call {
	_c.Run(run)
	return _c
}

// InclusionReport provides a mock function with no fields
func (_m *Thing) InclusionReport() *fimptype.ThingInclusionReport {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InclusionReport")
	}

	var r0 *fimptype.ThingInclusionReport
	if rf, ok := ret.Get(0).(func() *fimptype.ThingInclusionReport); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fimptype.ThingInclusionReport)
		}
	}

	return r0
}

// Thing_InclusionReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InclusionReport'
type Thing_InclusionReport_Call struct {
	*mock.Call
}

// InclusionReport is a helper method to define mock.On call
func (_e *Thing_Expecter) InclusionReport() *Thing_InclusionReport_Call {
	return &Thing_InclusionReport_Call{Call: _e.mock.On("InclusionReport")}
}

func (_c *Thing_InclusionReport_Call) Run(run func()) *Thing_InclusionReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Thing_InclusionReport_Call) Return(_a0 *fimptype.ThingInclusionReport) *Thing_InclusionReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Thing_InclusionReport_Call) RunAndReturn(run func() *fimptype.ThingInclusionReport) *Thing_InclusionReport_Call {
	_c.Call.Return(run)
	return _c
}

// SendConnectivityReport provides a mock function with given fields: force
func (_m *Thing) SendConnectivityReport(force bool) (bool, error) {
	ret := _m.Called(force)

	if len(ret) == 0 {
		panic("no return value specified for SendConnectivityReport")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(bool) (bool, error)); ok {
		return rf(force)
	}
	if rf, ok := ret.Get(0).(func(bool) bool); ok {
		r0 = rf(force)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(bool) error); ok {
		r1 = rf(force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Thing_SendConnectivityReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendConnectivityReport'
type Thing_SendConnectivityReport_Call struct {
	*mock.Call
}

// SendConnectivityReport is a helper method to define mock.On call
//   - force bool
func (_e *Thing_Expecter) SendConnectivityReport(force interface{}) *Thing_SendConnectivityReport_Call {
	return &Thing_SendConnectivityReport_Call{Call: _e.mock.On("SendConnectivityReport", force)}
}

func (_c *Thing_SendConnectivityReport_Call) Run(run func(force bool)) *Thing_SendConnectivityReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *Thing_SendConnectivityReport_Call) Return(_a0 bool, _a1 error) *Thing_SendConnectivityReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Thing_SendConnectivityReport_Call) RunAndReturn(run func(bool) (bool, error)) *Thing_SendConnectivityReport_Call {
	_c.Call.Return(run)
	return _c
}

// SendInclusionReport provides a mock function with given fields: force
func (_m *Thing) SendInclusionReport(force bool) (bool, error) {
	ret := _m.Called(force)

	if len(ret) == 0 {
		panic("no return value specified for SendInclusionReport")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(bool) (bool, error)); ok {
		return rf(force)
	}
	if rf, ok := ret.Get(0).(func(bool) bool); ok {
		r0 = rf(force)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(bool) error); ok {
		r1 = rf(force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Thing_SendInclusionReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendInclusionReport'
type Thing_SendInclusionReport_Call struct {
	*mock.Call
}

// SendInclusionReport is a helper method to define mock.On call
//   - force bool
func (_e *Thing_Expecter) SendInclusionReport(force interface{}) *Thing_SendInclusionReport_Call {
	return &Thing_SendInclusionReport_Call{Call: _e.mock.On("SendInclusionReport", force)}
}

func (_c *Thing_SendInclusionReport_Call) Run(run func(force bool)) *Thing_SendInclusionReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *Thing_SendInclusionReport_Call) Return(_a0 bool, _a1 error) *Thing_SendInclusionReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Thing_SendInclusionReport_Call) RunAndReturn(run func(bool) (bool, error)) *Thing_SendInclusionReport_Call {
	_c.Call.Return(run)
	return _c
}

// SendPingReport provides a mock function with no fields
func (_m *Thing) SendPingReport() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendPingReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Thing_SendPingReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPingReport'
type Thing_SendPingReport_Call struct {
	*mock.Call
}

// SendPingReport is a helper method to define mock.On call
func (_e *Thing_Expecter) SendPingReport() *Thing_SendPingReport_Call {
	return &Thing_SendPingReport_Call{Call: _e.mock.On("SendPingReport")}
}

func (_c *Thing_SendPingReport_Call) Run(run func()) *Thing_SendPingReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Thing_SendPingReport_Call) Return(_a0 error) *Thing_SendPingReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Thing_SendPingReport_Call) RunAndReturn(run func() error) *Thing_SendPingReport_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceByTopic provides a mock function with given fields: topic
func (_m *Thing) ServiceByTopic(topic string) adapter.Service {
	ret := _m.Called(topic)

	if len(ret) == 0 {
		panic("no return value specified for ServiceByTopic")
	}

	var r0 adapter.Service
	if rf, ok := ret.Get(0).(func(string) adapter.Service); ok {
		r0 = rf(topic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adapter.Service)
		}
	}

	return r0
}

// Thing_ServiceByTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceByTopic'
type Thing_ServiceByTopic_Call struct {
	*mock.Call
}

// ServiceByTopic is a helper method to define mock.On call
//   - topic string
func (_e *Thing_Expecter) ServiceByTopic(topic interface{}) *Thing_ServiceByTopic_Call {
	return &Thing_ServiceByTopic_Call{Call: _e.mock.On("ServiceByTopic", topic)}
}

func (_c *Thing_ServiceByTopic_Call) Run(run func(topic string)) *Thing_ServiceByTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Thing_ServiceByTopic_Call) Return(_a0 adapter.Service) *Thing_ServiceByTopic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Thing_ServiceByTopic_Call) RunAndReturn(run func(string) adapter.Service) *Thing_ServiceByTopic_Call {
	_c.Call.Return(run)
	return _c
}

// Services provides a mock function with given fields: name
func (_m *Thing) Services(name fimptype.ServiceNameT) []adapter.Service {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Services")
	}

	var r0 []adapter.Service
	if rf, ok := ret.Get(0).(func(fimptype.ServiceNameT) []adapter.Service); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]adapter.Service)
		}
	}

	return r0
}

// Thing_Services_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Services'
type Thing_Services_Call struct {
	*mock.Call
}

// Services is a helper method to define mock.On call
//   - name fimptype.ServiceNameT
func (_e *Thing_Expecter) Services(name interface{}) *Thing_Services_Call {
	return &Thing_Services_Call{Call: _e.mock.On("Services", name)}
}

func (_c *Thing_Services_Call) Run(run func(name fimptype.ServiceNameT)) *Thing_Services_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(fimptype.ServiceNameT))
	})
	return _c
}

func (_c *Thing_Services_Call) Return(_a0 []adapter.Service) *Thing_Services_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Thing_Services_Call) RunAndReturn(run func(fimptype.ServiceNameT) []adapter.Service) *Thing_Services_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0
func (_m *Thing) Update(_a0 ...adapter.ThingUpdate) error {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...adapter.ThingUpdate) error); ok {
		r0 = rf(_a0...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Thing_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Thing_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 ...adapter.ThingUpdate
func (_e *Thing_Expecter) Update(_a0 ...interface{}) *Thing_Update_Call {
	return &Thing_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{}, _a0...)...)}
}

func (_c *Thing_Update_Call) Run(run func(_a0 ...adapter.ThingUpdate)) *Thing_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]adapter.ThingUpdate, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(adapter.ThingUpdate)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Thing_Update_Call) Return(_a0 error) *Thing_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Thing_Update_Call) RunAndReturn(run func(...adapter.ThingUpdate) error) *Thing_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewThing creates a new instance of Thing. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewThing(t interface {
	mock.TestingT
	Cleanup(func())
}) *Thing {
	mock := &Thing{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
